import type { Lang } from '@/lib/i18n';

export interface CultureItem {
  title: string;
  desc: string;
  photo: string;
  by: string;
  contentSource?: string;
  photoSource?: string;
  exploreLink?: string;
}

// Written by team members from their own culture-intro submissions (Word docs).
// `by` is intentionally the same English-name string across all three languages.
export const CULTURE_ITEMS: Record<Lang, CultureItem[]> = {
  ko: [
    {
      title: '한글',
      desc: '한글은 1443년 조선의 제4대 왕 세종대왕이 백성들을 위해 창제한 독창적인 문자입니다. 세계에서 유일하게 창제자와 창제 연도, 원리가 명확하게 기록된 문자로, 과학성과 체계성을 널리 인정받고 있습니다. 발음 기관의 모양을 본떠 만든 자음과 천·지·인의 원리를 담은 모음이 결합하여 수많은 소리를 표현할 수 있습니다. 1997년에는 유네스코 세계기록유산으로 훈민정음 해례본이 등재되며 그 역사적 가치를 세계적으로 인정받았습니다. 오늘날에도 정보화 시대에 가장 적합한 문자로 평가받으며 한국 문화의 핵심적인 역할을 하고 있습니다.',
      photo: '/uploads/culture/culture-01.jpg',
      by: 'by. Su-been Wang',
      contentSource: '국립한글박물관. (2026). 「한글의 역사」. 국립한글박물관. https://www.hangeul.go.kr/. (접속일: 2026.08.21.)',
      photoSource: '국립한글박물관. (2026). 「훈민정음 해례본」.',
      exploreLink: 'https://www.hangeul.go.kr/ (국립한글박물관)',
    },
    {
      title: '수능',
      desc: '수능이란 대학수학능력시험의 줄임말로 대학에서의 수학능력을 평가하는 시험입니다. 수능은 일 년에 단 한 번, 11월 중순쯤 치러집니다. 이 시험은 대학 입학에 사용되고 주로 정시와 수시 교과 전형에서 활용됩니다. 시험 과목은 국어, 수학, 영어, 한국사, 사회탐구, 과학탐구, 직업탐구, 제2외국어/한문으로 구성되어 있고, 수험생마다 필요한 과목이 모두 다릅니다. 수능은 절대평가가 아닌 상대평가로 성적이 나오는 시험으로, 1등급부터 9등급까지 존재하며 숫자가 낮을수록 좋은 성적입니다.',
      photo: '/uploads/culture/culture-02.jpg',
      by: 'by. Ju-hyun Kwak',
      photoSource: '한국교육과정평가원. https://www.kice.re.kr/main.do?s=kice. (접속일: 2026.08.21.)',
      contentSource: '현재 한국에서 고등학교 3학년에 재학 중인 학생의 경험담. (Ju-hyun Kwak 피셜)',
    },
    {
      title: '한복',
      desc: '한복은 오랜 역사 속에서 발전해 온 한국의 전통 의상입니다. 고구려 고분 벽화와 신라의 토우 등에서 초기 형태를 확인할 수 있으며, 삼국시대에 오늘날 한복의 기본 구조인 저고리와 치마·바지가 자리 잡았습니다. 몸을 꽉 조이지 않고 넉넉하게 만들어 편안하며, 직선과 곡선이 조화를 이루어 단정하고 우아한 느낌을 줍니다. 과거에는 신분과 계절, 상황에 따라 소재와 색상이 달랐으나 오늘날에는 명절이나 예식 등 특별한 날에 주로 착용합니다. 최근에는 전통 양식에 현대적 실용성을 더한 \'생활한복\'과 \'개량한복\'이 젊은 세대의 일상 패션으로 자리 잡으며, K-pop과 한국 드라마의 열풍으로 해외에서도 한국의 아름다움을 알리는 의상으로 주목받고 있습니다.',
      photo: '/uploads/culture/culture-03.jpg',
      by: 'by. Ye-eun Kim',
      contentSource: "한국학중앙연구원 《한국민족문화대백과사전》 '한복' 항목. https://encykorea.aks.ac.kr/Article/E0061645",
      photoSource: '교육부 국립특수교육원. (2020). 「한복에 담긴 조상의 지혜 알기」. https://www.nise.go.kr/sedu/2020/sw_p/pr2/pr1_2/page02.html',
      exploreLink: "문화체육관광부 국립민속박물관 한국문화상자 '한복' 상자. https://www.nfm.go.kr/k-box/ui/hanbok/introduce.do",
    },
    {
      title: 'K-pop',
      desc: 'K-pop은 한국에서 만들어져 전 세계적으로 사랑받는 대중음악 장르로, 중독성 있는 후크송과 화려한 군무가 특징입니다. 2005년 보아와 동방신기가 일본 오리콘 차트 상위권에 오르며 해외 진출의 첫 발판을 마련했고, 2012년 싸이의 \'강남스타일\'이 빌보드 Hot 100에서 2위에 오르며 미국 대중음악 시장에 본격적으로 알려졌습니다. 이후 방탄소년단(BTS)이 빌보드 \'핫 100\' 차트에서 여러 차례 1위를 차지하며 K-pop의 위상을 세계적으로 끌어올렸고, 최근에는 BLACKPINK, Stray Kids, TWICE, NewJeans 등도 해외에서 큰 인기를 얻고 있습니다. K-pop은 음악을 넘어 영화·애니메이션 등 다양한 콘텐츠와 결합하며 더욱 널리 퍼지고 있으며, 해외 팬들이 한국어를 배우거나 한국 음식과 드라마에 관심을 갖는 등 한류 확산의 중심 역할을 하고 있습니다.',
      photo: '/uploads/culture/culture-04.jpg',
      by: 'by. So-jeong Kim',
      contentSource: "한국민족문화대백과사전 '케이팝' 항목. https://encykorea.aks.ac.kr/Article/E0073667",
      photoSource: '제출자 직접 촬영 (콘서트 현장, 별도 출처 표기 없음)',
      exploreLink: "한국민족문화대백과사전 '케이팝'. https://encykorea.aks.ac.kr/Article/E0073667",
    },
    {
      title: '태권도',
      desc: '태권도는 호신과 자아실현을 목적으로, 타격 방식의 차기에 특화된 맨손 방어와 공격 기술을 수련하는 무예 스포츠입니다. 태권도의 5대 덕목은 극기와 홍익을 일상생활에서 실제로 구현하기 위한 행동 지침으로, 인내·용기·예의·정의·봉사로 이루어져 있습니다. 올림픽 정식 종목으로도 채택되어 전 세계 선수들이 기량을 겨루는 무대가 되었으며, 한국을 대표하는 전통 무술이자 현대 스포츠로서 국내외에서 폭넓게 사랑받고 있습니다.',
      photo: '/uploads/culture/culture-05.jpg',
      by: 'by. Eun-woo Park',
      photoSource: "올림픽 홈페이지. Marta Martín. (2022.06.22.). 「파리 2024 종목별 체급: 올림픽 태권도 경기」. https://www.olympics.com/ko/news/paris-2024-weight-categories-for-olympic-taekwondo",
      contentSource: '대한태권도협회(국기원) 홈페이지. https://www.kukkiwon.or.kr',
      exploreLink: 'https://www.kukkiwon.or.kr/base/board/list?boardManagementNo=37&menuLevel=3&menuNo=62',
    },
    {
      title: '한국의 시험 응원 문화',
      desc: '한국에서는 중요한 시험을 앞둔 사람에게 엿이나 찹쌀떡을 선물하며 합격을 기원하는 문화가 있습니다. 엿과 찹쌀떡은 끈적하고 잘 달라붙는 특성 때문에 "시험에 착 붙는다", 즉 원하는 결과를 얻고 합격하기를 바라는 의미를 담고 있습니다. 특히 대학수학능력시험이나 대학 입시처럼 중요한 시험을 앞둔 학생에게 가족, 친구, 선생님 등이 엿이나 찹쌀떡을 건네며 응원의 마음을 전합니다. 실제로 엿의 엿당은 짧은 시간 안에 분해되어 두뇌에 영양 공급을 도울 수도 있다고 합니다. 이처럼 한국의 시험 응원 문화는 일상적인 음식에 소망과 마음을 담아 서로에게 힘을 전하는 한국만의 독특한 응원 방식입니다.',
      photo: '/uploads/culture/culture-06.jpg',
      by: 'by. Bo-seong Kwon',
      contentSource: 'https://www.thinkfood.co.kr/news/articleView.html?idxno=90269',
      photoSource: '경인일보, 나무위키',
      exploreLink: 'https://www.nongmin.com/article/20141108269230',
    },
    {
      title: '고려청자',
      desc: '고려청자는 고려 시대에 제작된 대표적인 도자기로, 특히 12~13세기에 걸쳐 높은 수준으로 발전하였습니다. 청록색을 띠는 유약을 사용한 것이 특징이며, 이러한 색은 흔히 \'비색\'이라고 불립니다. 대표적인 장식 기법으로는 상감 기법이 있는데, 도자기 표면에 무늬를 새긴 뒤 그 부분에 다른 색의 흙을 채우고 유약을 발라 구워 무늬를 나타내는 방법입니다. 연꽃, 국화, 구름, 학, 물고기 등 자연물을 비롯한 다양한 문양이 사용되었으며, 초기에는 중국 도자기 기술의 영향을 받았지만 점차 독자적인 제작 방식과 형태, 색채를 갖추게 되었습니다. 생활용품뿐 아니라 의례용품과 장식품 등 다양한 용도로 제작되어, 당시 고려의 도자기 제작 기술과 공예 수준을 보여주는 중요한 문화유산입니다.',
      photo: '/uploads/culture/culture-07.jpg',
      by: 'by. Gyeong-been Lim',
      contentSource: '나무위키, 전통문화포털',
      photoSource: '나무위키, 전통문화포털',
      exploreLink: 'https://www.khs.go.kr (국가유산청)',
    },
    {
      title: '한국의 급식',
      desc: '한국의 학교 급식은 스테인리스 식판에 균형 잡힌 갓 조리한 한 끼를 담아내는 것이 특징입니다. 밥과 국을 기본으로, 불고기·돈가스·조림·생선구이 같은 메인 반찬과 나물·계란말이·샐러드, 그리고 늘 빠지지 않는 김치가 함께 나옵니다. 전문 영양사와 조리 인력이 상주하며 열량·나트륨·영양소를 세심하게 계산해 신선한 재료로 매일 새롭게 조리합니다. 로제떡볶이나 랍스터, 치즈크러스트 피자 같은 트렌디한 메뉴부터 타코·쌀국수 같은 세계 음식의 날, 시험 기간의 격려 메시지가 담긴 떡까지 다양한 특별 메뉴도 운영됩니다.',
      photo: '/uploads/culture/culture-08.jpg',
      by: 'by. Seo-jin Baek',
      contentSource: 'AI',
      photoSource: 'AI',
    },
    {
      title: '김치',
      desc: '김치는 배추, 무와 같은 채소에 고춧가루, 마늘, 생강 등의 양념을 넣어 발효시켜 만든 한국의 전통 음식입니다. 한국에서는 김치가 거의 매일 식탁에 오르며, 지역과 재료에 따라 다양한 종류의 김치가 있습니다. 발효 과정을 거치기 때문에 특유의 깊은 맛이 나는 것이 특징이며, 특히 추운 겨울을 준비하기 위해 가족과 이웃이 함께 많은 양의 김치를 담그는 \'김장\' 문화가 있습니다. 김장은 가족과 이웃이 함께 모여 김치를 담그며 한국의 공동체 문화를 보여주는 대표적인 풍습으로, 이러한 \'김장, 김치를 담그고 나누는 문화\'는 2013년 유네스코 인류무형문화유산으로 등재되었습니다.',
      photo: '/uploads/culture/culture-09.jpg',
      by: 'by. Yeon-ji Jo',
      contentSource: "공정식 기자. (2026.08.20.). 「영남대 '사랑의 김치 나눔'」. https://naver.me/5yhoOkCK",
      photoSource: "공정식 기자. (2026.08.20.). 「영남대 '사랑의 김치 나눔'」. https://naver.me/5yhoOkCK",
    },
    {
      title: "한국의 '빨리빨리' 문화",
      desc: '한국에는 \'빨리빨리\'라는 독특한 문화가 있습니다. 한국 사람들은 일상생활에서 기다리는 시간을 줄이고 빠르게 일을 처리하는 것을 중요하게 생각합니다. 식당에서는 주문한 음식이 빠르게 나오고, 카페에서는 키오스크나 모바일 주문을 통해 간편하게 주문할 수 있습니다. 대중교통도 실시간으로 도착 정보를 확인할 수 있어 시간을 효율적으로 사용할 수 있고, 온라인으로 옷이나 생필품, 음식을 주문하면 다음 날 바로 받아볼 수 있을 정도로 빠른 배송이 발달해 있습니다. 은행이나 병원에서도 번호표와 자동화 시스템을 이용해 불필요한 대기 시간을 줄이는 등, \'빨리빨리\' 문화는 시간을 아끼고 빠르게 원하는 것을 얻으려는 한국인의 생활방식을 잘 보여줍니다.',
      photo: '/uploads/culture/culture-10.jpg',
      by: 'by. Si-won Song',
      photoSource: '본인 캡쳐',
    },
    {
      title: '한옥',
      desc: '한옥은 한국의 전통적인 주거 건축물로, 한국의 기후와 생활 방식에 맞게 발전한 건축 형태입니다. 주로 나무, 흙, 돌, 한지 등의 재료를 사용하며, 대표적인 구조로 온돌과 마루가 있습니다. 온돌은 아궁이에서 발생한 열을 방바닥 아래로 전달해 실내를 난방하는 방식으로 추운 겨울에 적합하고, 마루는 바닥을 지면에서 띄워 바람이 통하도록 만든 공간으로 주로 여름철에 이용됩니다. 지붕은 기와를 사용한 경우가 많으며 처마가 돌출되어 있어 계절에 따라 실내로 들어오는 햇빛의 양을 조절하고, 창호에는 한지를 사용해 빛을 받아들이면서 공기가 통하게 했습니다. 이러한 구조를 통해 한옥은 겨울에는 온돌로 난방하고 여름에는 마루와 통풍을 활용하는 등 계절에 따라 실내 환경을 조절할 수 있도록 설계되었습니다.',
      photo: '/uploads/culture/culture-11.jpg',
      by: 'by. Gyeong-been Lim',
      contentSource: '행정안전부 국가기록관; 대한건축사협회 건축사신문, 「[2021 한옥정책 점검③] 한옥정책, 앞으로의 10년」',
      photoSource: '행정안전부 국가기록관; 대한건축사협회 건축사신문, 「[2021 한옥정책 점검③] 한옥정책, 앞으로의 10년」',
      exploreLink: 'https://hanok.seoul.go.kr/front/kor/info/infoHanok.do?tab=2 (한옥 구조)',
    },
    {
      title: '한국의 목욕문화 사우나(찜질방)',
      desc: '한국 여행이나 일상에서 쌓인 피로를 날려버리고 싶다면 찜질방과 대중목욕탕이 제격입니다. 단순히 몸을 씻는 곳을 넘어 한국 고유의 힐링 문화를 온몸으로 체험할 수 있는 공간입니다. 여러 사람이 함께 탕을 공유하는 문화인 만큼 온수탕이나 냉탕에 들어가기 전 샤워로 몸을 깨끗이 씻는 것이 가장 중요한 에티켓이며, 긴 머리는 묶어 올리거나 수건으로 감싸 물에 닿지 않게 배려해야 합니다. 뜨끈한 황토방과 소금방에서 땀을 뺀 뒤 얼음방으로 이동해 열기를 식히는 테마 사우나, 살얼음 뜬 식혜와 맥반석 구운 계란 같은 시그니처 간식, 수건으로 \'양머리\'를 만들어 쓰는 재미있는 인증샷 포인트까지 — 찜질방은 몸과 마음을 함께 풀어주는 한국인의 대표적인 휴식 문화입니다.',
      photo: '/uploads/culture/culture-12.jpg',
      by: 'by. Seo-jin Baek',
      contentSource: '2026.06.29. Enkostay blog. 「한국 대중목욕탕 이용 방법: 첫 찜질방 방문을 위한 완벽한 가이드」. https://stay.enko.kr/blog/ko/',
      photoSource: '2026.06.29. Enkostay blog. 「한국 대중목욕탕 이용 방법: 첫 찜질방 방문을 위한 완벽한 가이드」. https://stay.enko.kr/blog/ko/',
    },
    {
      title: '곶감',
      desc: '곶감은 껍질을 깎은 감을 햇볕과 바람이 잘 통하는 곳에서 오랫동안 말려 만드는 대한민국 대표 전통 건과일입니다. 건조 과정을 거치면서 감 특유의 떫은맛은 자연스럽게 사라지고 단맛이 배가되어 겉은 쫀득하고 속은 부드러운 독특한 식감을 지니게 됩니다. 과거에는 겨울철 영양을 보충하는 귀한 간식이자 삼색실과 중 하나로서 제례나 명절 차례상에 필수적으로 올려졌습니다. 비타민 A와 C가 풍부하여 면역력 강화와 감기 예방에 뛰어난 효과가 있으며, 한의학적으로는 목의 통증 완화와 숙취 해소에도 효능이 있는 것으로 전해집니다. 최근에는 호두나 치즈를 감싸 만든 곶감말이 등 현대적인 디저트로도 재해석되어 남녀노소 모두에게 사랑받는 고급 K-푸드로 자리매김하고 있습니다.',
      photo: '/uploads/culture/culture-13.jpg',
      by: 'by. Su-A Choi',
      contentSource: '농촌진흥청. (2023.11.15.). 「한국의 농식품 종합정보: 곶감의 효능과 역사」. 농사로. https://www.nongsaro.go.kr (접속일: 2026.08.14.)',
      photoSource: '네이원. (2026.05.22.). 「쫀득쫀득한 간식거리 상주곶감」. 네이버 블로그. https://m.blog.naver.com/wntlr6012/224293796772 (접속일: 2026.08.14.)',
    },
    {
      title: '한국의 배달 문화',
      desc: '한국의 배달 문화는 빠르고 편리함을 추구하는 특유의 정서와 결합하여 세계적으로 독특한 형태로 발전했습니다. 언제 어디서든 스마트폰 앱 터치 몇 번이면 따뜻한 음식부터 생필품까지 신속하게 문 앞까지 배달됩니다. 특히 한강 공원이나 야외에서 치킨 등을 배달시켜 먹는 것은 내국인뿐만 아니라 외국인 관광객들에게도 필수 체험으로 꼽힙니다. 최근에는 친환경 다회용기 사용 등 환경을 고려한 배달 방식도 점차 도입되며 성숙해지고 있습니다. 이러한 배달 산업은 단순한 음식 배달 서비스를 넘어 뛰어난 IT 인프라와 일상생활이 융합된 대표적인 현대 문화입니다.',
      photo: '/uploads/culture/culture-14.jpg',
      by: 'by. Su-been Wang',
      contentSource: '한국관광공사. (2026). 「한국의 배달 문화 체험」. 대한민국 구석구석. https://korean.visitkorea.or.kr/. (접속일: 2026.08.21.)',
      photoSource: '한국관광공사. (2026). 「한강 공원 배달 음식」.',
      exploreLink: 'https://korean.visitkorea.or.kr/ (대한민국 구석구석)',
    },
    {
      title: '독도',
      desc: '독도는 동해의 최동단에 위치한 대한민국의 영토로, 울릉도에서 동남쪽으로 약 87.4km 떨어져 있습니다. 동도와 서도 두 개의 큰 섬과 주변의 작은 부속 도서로 이루어져 있으며, 총면적은 약 187,554㎡이고 행정구역상 경상북도 울릉군 울릉읍 독도리에 속합니다. 1900년 대한제국 고종은 칙령 제41호를 통해 독도를 울릉군의 관할 구역으로 명시하였습니다. 독도는 다양한 해양 생물과 철새가 서식하는 생태계의 보고이며 천연기념물 제336호로 지정되어 보호받고 있습니다. 대한민국의 자연과 역사, 주권을 상징하는 소중한 장소로 여겨지고 있습니다.',
      photo: '/uploads/culture/culture-15.jpg',
      by: 'by. So-jeong Kim',
      contentSource: 'Wikimedia Commons, Category:Liancourt Rocks. https://commons.wikimedia.org/wiki/Category:Liancourt_Rocks (접속일: 2026.08.20.)',
      photoSource: 'Wikimedia Commons, Category:Liancourt Rocks. https://commons.wikimedia.org/wiki/Category:Liancourt_Rocks (접속일: 2026.08.20.)',
      exploreLink: '대한민국 외교부 독도 누리집: https://dokdo.mofa.go.kr/kor/',
    },
    {
      title: '야구 응원 문화',
      desc: '한국의 야구 경기장은 단순히 경기를 관람하는 곳일 뿐만 아니라 팬들이 함께 응원하고 즐기는 문화 공간입니다. 한국프로야구는 각 팀마다 고유한 응원가와 구호가 있어 팬들이 선수의 이름을 외치며 함께 노래합니다. 경기장에는 응원단장과 치어리더가 팬 응원을 이끌고, 관중들은 박수와 율동을 하며 하나가 됩니다. 특히 응원가에 맞춰 수천 명의 관중이 동시에 함께 춤추는 모습은 한국에서만 볼 수 있는 독특한 문화이며, 팬들은 자신이 응원하는 팀의 색깔에 맞는 유니폼과 응원 도구를 사용하며 열정을 표현합니다. 이처럼 한국의 야구 응원 문화는 단순히 경기를 관람하는 것을 넘어 팬들이 함께 참여하고 즐기는 축제와 같은 문화라고 할 수 있습니다.',
      photo: '/uploads/culture/culture-16.jpg',
      by: 'by. Yeon-ji Jo',
      contentSource: '주현희 기자. (2023.10.22.). 「랜더스 응원 가득한 응원 깃발」. 스포츠동아. https://naver.me/lGsQxidS',
      photoSource: '주현희 기자. (2023.10.22.). 「랜더스 응원 가득한 응원 깃발」. 스포츠동아. https://naver.me/lGsQxidS',
    },
    {
      title: '자개(나전칠기)',
      desc: '자개는 전복, 소라, 진주조개 등의 껍데기 안쪽을 얇게 가공해 만든 한국의 전통 공예 재료로, 빛을 받는 각도에 따라 여러 색으로 반짝이는 것이 가장 큰 특징입니다. 오래전부터 가구, 상자, 소반 등의 장식에 사용되었으며, 고려시대부터 자개를 활용한 공예가 크게 발전했습니다. 자개 조각을 꽃, 나뭇잎, 새와 같은 다양한 모양으로 오려 나무 제품에 붙이고 옻칠을 더해 만든 공예품을 나전칠기라고 합니다. 과거에는 왕실과 상류층의 가구나 생활용품을 장식하는 데 주로 사용되었지만, 오늘날에는 전통적인 아름다움을 현대적으로 재해석하여 스마트폰 케이스, 보석함, 인테리어 소품 등에도 활용되고 있습니다.',
      photo: '/uploads/culture/culture-17.jpg',
      by: 'by. Ye-eun Kim',
      contentSource: "한국학중앙연구원 《한국민족문화대백과사전》 '나전칠기' 항목. https://encykorea.aks.ac.kr/Article/E0011448",
      photoSource: '「나전 칠 연꽃 모란넝쿨 무늬 상자」, 국립중앙박물관. https://www.museum.go.kr/MUSEUM/contents/M0502000000.do?schM=view&searchId=search&relicId=1338',
      exploreLink: '서울특별시 무형유산 손대현 옻칠장의 나전칠기 제작 모습. https://youtu.be/srHROM_qI9Q',
    },
    {
      title: '한국의 찜질방 문화',
      desc: '한국의 찜질방은 목욕과 휴식을 함께 즐길 수 있는 한국의 독특한 문화입니다. 여러 종류의 뜨거운 찜질방에서 땀을 빼고, 편안한 휴게 공간에서 쉴 수 있습니다. 친구나 가족과 함께 방문해 이야기를 나누며 시간을 보내기도 하고, 식혜와 삶은 계란 같은 대표적인 음식도 즐길 수 있습니다. 또한 24시간 운영하는 곳이 많아 잠을 자거나 여행 중 쉬어가는 장소로 이용하기도 합니다. 이처럼 찜질방은 단순히 목욕하는 곳을 넘어 한국인들의 휴식과 여가 문화를 경험할 수 있는 공간입니다.',
      photo: '/uploads/culture/culture-18.jpg',
      by: 'by. Si-won Song',
      contentSource: '본인 촬영',
      photoSource: '본인 촬영',
      exploreLink: 'https://ichpedia.org/ich/detail?id=43418',
    },
    {
      title: '단청',
      desc: '단청의 사전적 의미는 옛날식 집의 벽, 기둥, 천장 따위에 여러 가지 빛깔로 그림이나 무늬를 그리는 것, 또는 그 그림이나 무늬, 그리고 여러 가지의 고운 빛깔을 뜻합니다. 이러한 단청은 목조 건축물의 격조를 높이는 장엄의 의미와, 방충·방습으로 인한 목재의 수명을 연장시키기 위한 실용적인 목적을 함께 지니고 있습니다. 또한 종교 등 신앙적인 의례의 표현으로 일반 건조물과 구별하는 의미도 내재되어 있어, 궁궐과 사찰 등 격식 있는 건축물에서 주로 볼 수 있습니다.',
      photo: '/uploads/culture/culture-19.jpg',
      by: 'by. Ju-hyun Kwak',
      contentSource: "한국학중앙연구원. 향토문화전자대전. 조춘용 집필. 「단청장」. https://www.grandculture.net/cheongju/dir/GC00202036 (접속일: 2026.08.21.)",
      photoSource: '국가유산청. 「19585_기둥 상부 용두 단청_단청장」. 국가유산청 국가유산포털. https://www.heritage.go.kr/heri/cul/culSelectDetail.do?ccbaKdcd=17&ccbaAsno=0000480000000&ccbaCtcd=38&pageNo=1_1_1_0 (접속일: 2026.08.21.)',
      exploreLink: 'https://royal.khs.go.kr/ROYAL/contents/R403000000.do?schM=view&id=20080501122000000045',
    },
    {
      title: '한국의 호칭 문화',
      desc: '한국의 호칭 문화는 사람과 사람 사이의 \'존중\'과 \'친밀함\'을 표현하는 언어입니다. 한국에서는 상대방과의 나이, 관계, 사회적 위치, 친밀도에 따라 서로 다른 호칭을 사용합니다. 특히 가까운 사이에서는 피가 섞이지 않았더라도 나이가 많은 사람을 \'형, 누나, 언니, 오빠\'라고 부르며 가족과 같은 친밀함을 표현합니다. 반대로 공식적인 자리에서는 \'선생님, 사장님, 기사님\'처럼 상대방의 역할과 위치를 나타내는 호칭을 사용하며 예의를 갖춥니다. 이처럼 누군가를 어떻게 부르는지가 곧 그 사람과 나의 관계를 보여주는 하나의 문화적 표현이 되며, 호칭을 통해 상대를 존중하면서도 때로는 가족처럼 가까이 받아들이는 한국인의 관계 중심적 가치관을 엿볼 수 있습니다.',
      photo: '/uploads/culture/culture-20.jpg',
      by: 'by. Bo-seong Kwon',
      contentSource: '국립국어원. 「표준언어예절 - 사회에서의 호칭·지칭」.',
      photoSource: 'AI 생성 이미지 (원본 출처 미기재)',
      exploreLink: '표준언어예절 - 사회에서의 호칭·지칭 (국립국어원)',
    },
    {
      title: '한국의 전통음식',
      desc: '한국 전통 음식은 주식과 부식이 구분되고, 음식을 모두 한 상에 차려 놓고 먹는 것이 특징입니다. 지역과 계절에 따른 음식이 발달하였고, 국물 음식이 많아 숟가락과 젓가락을 함께 사용합니다. 기본 곡류 식품에 채소류·육류·생선류 등 다양한 반찬을 곁들여 영양적으로 균형 잡힌 식사를 구성하며, 기름을 많이 쓰지 않고 구이·찜·데침·무침 조리법을 활용해 저열량 식사를 만듭니다. 약식동원(藥食同源)에 따라 파·마늘·생강 등 향이 강한 양념을 많이 사용하는데, 이는 몸을 보호해 주는 약재의 효과도 함께 지니고 있습니다. 또한 발효 음식이 크게 발달한 것도 한국 전통 음식의 중요한 특징입니다.',
      photo: '/uploads/culture/culture-21.jpg',
      by: 'by. Eun-woo Park',
      contentSource: '김현철(서울 영동고 역사교사). (2024.10.01.). 「[신문은 선생님] 우리 전통 음식 비빔밥, 조선시대 땐 임금 친척에게 대접한 궁중 요리였죠」. 조선일보. https://www.chosun.com/national/nie/2024/10/01/P52BMQFKQFFUDMIBSZQFWM7RVM/',
      photoSource: '울산광역시교육청. https://school.use.go.kr/_cmm/fileDownload/yh-e/M01040903/10576dc097be65dd41afc32455cb54d5',
    },
    {
      title: '유과',
      desc: '유과는 찹쌀가루에 술과 물을 넣어 반죽한 뒤 찌고 말려서 기름에 튀겨낸 후, 조청과 고물을 묻혀 완성하는 한국의 대표적인 전통 한과입니다. 반죽을 기름에 튀기는 과정에서 내부에 미세한 공기층이 다량 형성되어, 입안에 넣었을 때 바삭하면서도 부드럽게 녹아내리는 특유의 식감을 선사합니다. 겉면에는 쌀가루, 튀밥, 깨 등의 고물을 묻혀 고소함을 더하며, 천연 재료를 활용해 다채로운 색을 입히기도 합니다. 조선시대에는 궁중 연회나 양반가의 잔치, 혼례 등 격식 있는 자리에 빠지지 않던 최고급 다과로 대접받았으며, 오늘날에도 명절 선물이자 현대적 K-디저트로 꾸준한 인기를 누리고 있습니다.',
      photo: '/uploads/culture/culture-22.jpg',
      by: 'by. Su-A Choi',
      contentSource: '한식진흥원. (2024.01.20.). 「한국의 전통 과자: 유과의 제조 과정과 특징」. 한식진흥원. https://www.hansik.or.kr (접속일: 2026.08.14.)',
      photoSource: '사임당. (2025.04.15.). 「[찹쌀 유과] 바삭하면서 사르르~ 녹는맛이 일품!」. 네이버 블로그. https://m.blog.naver.com/saimdangfood/223833662867 (접속일: 2026.08.14.)',
    },
  ],
  en: [
    {
      title: 'Hangul',
      desc: "Hangul is a script King Sejong the Great, the fourth king of Joseon, created for the people in 1443. It is the only script in the world whose creator, year of creation, and design principles are all clearly documented, and it is widely praised for its scientific structure. Its consonants are shaped after the mouth and tongue positions used to pronounce them, while its vowels are built from the principles of heaven, earth, and person, together allowing countless sounds to be represented. In 1997 the Hunminjeongeum Haerye, the book explaining Hangul's design, was inscribed on UNESCO's Memory of the World register. Even today it is considered one of the best-suited scripts for the digital age and remains central to Korean culture.",
      photo: '/uploads/culture/culture-01.jpg',
      by: 'by. Su-been Wang',
      contentSource: 'National Hangeul Museum. (2026). "History of Hangeul." https://www.hangeul.go.kr/ (accessed 2026.08.21)',
      photoSource: 'National Hangeul Museum. (2026). "Hunminjeongeum Haerye."',
      exploreLink: 'https://www.hangeul.go.kr/ (National Hangeul Museum)',
    },
    {
      title: 'Suneung (CSAT)',
      desc: "Suneung, short for the College Scholastic Ability Test, evaluates whether students are ready for university-level study. It is held only once a year, in mid-November. The score is used for university admission, mainly through the regular and early-decision academic tracks. The subjects include Korean, math, English, Korean history, social studies, science, vocational studies, and a second foreign language or Chinese characters — and each student only needs a different subset of them. Suneung is graded on a relative, nine-tier scale rather than a fixed pass/fail standard, where grade 1 is the best.",
      photo: '/uploads/culture/culture-02.jpg',
      by: 'by. Ju-hyun Kwak',
      photoSource: 'Korea Institute for Curriculum and Evaluation. https://www.kice.re.kr/main.do?s=kice (accessed 2026.08.21)',
      contentSource: "Written from personal experience as a current high school senior in Korea. (Ju-hyun Kwak's own account)",
    },
    {
      title: 'Hanbok',
      desc: "Hanbok is Korea's traditional clothing, shaped over a long history. Early forms can already be seen in Goguryeo tomb murals and Silla clay figurines, and by the Three Kingdoms period the basic structure of today's hanbok — jeogori (jacket) with chima (skirt) or baji (pants) — had taken shape. It is made loose rather than fitted, so it is comfortable to wear, and its blend of straight and curved lines gives it a neat, elegant silhouette. Fabric and color once varied by social class, season, and occasion; today hanbok is mostly worn on holidays and formal ceremonies. Recently, \"saenghwal hanbok\" and \"gaeryang hanbok\" — traditional styles updated for everyday practicality — have become popular among younger generations, and the K-pop and K-drama wave has drawn international attention to hanbok as a symbol of Korean beauty.",
      photo: '/uploads/culture/culture-03.jpg',
      by: 'by. Ye-eun Kim',
      contentSource: 'Academy of Korean Studies, Encyclopedia of Korean Culture, entry "Hanbok." https://encykorea.aks.ac.kr/Article/E0061645',
      photoSource: 'Ministry of Education, National Institute of Special Education. (2020). "Understanding the Wisdom Behind Hanbok." https://www.nise.go.kr/sedu/2020/sw_p/pr2/pr1_2/page02.html',
      exploreLink: "Ministry of Culture, Sports and Tourism, National Folk Museum of Korea — 'Hanbok' Culture Box. https://www.nfm.go.kr/k-box/ui/hanbok/introduce.do",
    },
    {
      title: 'K-pop',
      desc: "K-pop is a genre of popular music that originated in Korea and is now loved worldwide, known for catchy hooks and polished group choreography. BoA and TVXQ topping Japan's Oricon chart in 2005 opened the first door overseas, and PSY's \"Gangnam Style\" reaching No. 2 on the Billboard Hot 100 in 2012 introduced K-pop to the US mainstream. BTS then took the K-pop's global standing further with multiple Billboard Hot 100 No. 1s, and groups like BLACKPINK, Stray Kids, TWICE, and NewJeans continue to draw huge audiences abroad. Agencies train trainees for years in singing, dancing, and languages to deliver highly polished performances, and K-pop has expanded beyond music into film and animation, drawing overseas fans toward Korean language, food, and dramas as part of the broader Hallyu wave.",
      photo: '/uploads/culture/culture-04.jpg',
      by: 'by. So-jeong Kim',
      contentSource: 'Encyclopedia of Korean Culture, entry "K-pop." https://encykorea.aks.ac.kr/Article/E0073667',
      photoSource: 'Taken by the submitter at a live concert (no further source given)',
      exploreLink: 'Encyclopedia of Korean Culture, entry "K-pop." https://encykorea.aks.ac.kr/Article/E0073667',
    },
    {
      title: 'Taekwondo',
      desc: 'Taekwondo is a martial sport built around self-defense and self-realization, specializing in unarmed striking techniques centered on kicks. Its five tenets translate the abstract ideals of self-control and benefiting humanity into everyday conduct: perseverance, courage, courtesy, integrity, and self-control (often listed alongside service). Now an official Olympic sport, it brings athletes from around the world together to compete, standing today as both a traditional Korean martial art and a modern global sport beloved at home and abroad.',
      photo: '/uploads/culture/culture-05.jpg',
      by: 'by. Eun-woo Park',
      photoSource: 'Olympics official site. Marta Martín. (2022.06.22). "Paris 2024 weight categories for Olympic taekwondo." https://www.olympics.com/en/news/paris-2024-weight-categories-for-olympic-taekwondo',
      contentSource: 'Kukkiwon (World Taekwondo Headquarters) official site. https://www.kukkiwon.or.kr',
      exploreLink: 'https://www.kukkiwon.or.kr/base/board/list?boardManagementNo=37&menuLevel=3&menuNo=62',
    },
    {
      title: 'Exam Cheering Culture',
      desc: 'In Korea, it\'s common to gift someone facing an important exam a piece of yeot (taffy) or chapssaltteok (sweet rice cake) to wish them success. Because both are sticky and cling easily, the gesture plays on the idea of "sticking" to a passing result. Family, friends, and teachers often hand these treats to students before the CSAT or other major exams as a way of showing support — and the natural sugars in yeot are even said to break down quickly enough to give the brain a quick energy boost. It\'s a distinctly Korean way of cheering someone on: wrapping hope and encouragement into an everyday food.',
      photo: '/uploads/culture/culture-06.jpg',
      by: 'by. Bo-seong Kwon',
      contentSource: 'https://www.thinkfood.co.kr/news/articleView.html?idxno=90269',
      photoSource: 'Gyeongin Ilbo; Namuwiki',
      exploreLink: 'https://www.nongmin.com/article/20141108269230',
    },
    {
      title: 'Goryeo Celadon',
      desc: 'Goryeo celadon is the signature pottery of the Goryeo dynasty, reaching its technical peak in the 12th–13th centuries. Its defining feature is a blue-green glaze commonly called "bisaek" (jade color). Its best-known decorative technique, sanggam inlay, involves carving a design into the clay surface, filling it with clay of a different color, then glazing and firing it to reveal the pattern. Motifs ranged from lotus flowers and chrysanthemums to clouds, cranes, and fish; while early pieces show Chinese influence, Goryeo potters gradually developed their own distinctive forms, shapes, and colors. Made for everyday use as well as rituals and decoration, Goryeo celadon is an important cultural heritage that showcases the ceramic craftsmanship of its era.',
      photo: '/uploads/culture/culture-07.jpg',
      by: 'by. Gyeong-been Lim',
      contentSource: 'Namuwiki; Korean Traditional Culture Portal',
      photoSource: 'Namuwiki; Korean Traditional Culture Portal',
      exploreLink: 'https://www.khs.go.kr (Korea Heritage Service)',
    },
    {
      title: 'Korean School Lunches',
      desc: "Every student in Korea gets a balanced, freshly cooked meal on a stainless-steel sectioned tray. Rice and soup form the base, joined by a main protein like bulgogi, tonkatsu, or grilled fish, vegetable and egg side dishes, and kimchi at every meal. On-site certified nutritionists and kitchen staff calculate each meal's calories, sodium, and nutrients using fresh ingredients, unlike schools that rely on packed lunches or processed cafeteria food. Cafeterias also run special-menu days — trending dishes like rose tteokbokki or cheese-crust pizza, global cuisine days featuring tacos or pho, and encouraging treats like rice cakes during exam season.",
      photo: '/uploads/culture/culture-08.jpg',
      by: 'by. Seo-jin Baek',
      contentSource: 'AI',
      photoSource: 'AI',
    },
    {
      title: 'Kimchi',
      desc: 'Kimchi is a traditional Korean dish made by fermenting vegetables such as napa cabbage or radish with seasonings like red pepper flakes, garlic, and ginger. It appears on Korean tables almost every day, with countless regional and seasonal varieties. Fermentation gives it a distinctive deep flavor, and to prepare for winter, families and neighbors traditionally gather to make large batches together in a custom called "kimjang." Kimjang shows off Korea\'s communal culture in action, and this tradition of making and sharing kimchi was inscribed on UNESCO\'s Representative List of the Intangible Cultural Heritage of Humanity in 2013.',
      photo: '/uploads/culture/culture-09.jpg',
      by: 'by. Yeon-ji Jo',
      contentSource: 'Gong Jeong-sik, reporter. (2026.08.20). "Yeungnam University \'s Kimchi of Love\' sharing event." https://naver.me/5yhoOkCK',
      photoSource: 'Gong Jeong-sik, reporter. (2026.08.20). "Yeungnam University \'s Kimchi of Love\' sharing event." https://naver.me/5yhoOkCK',
    },
    {
      title: "'Pali-pali' (Hurry-hurry) Culture",
      desc: 'Korea has a distinctive culture known as "pali-pali" — hurry, hurry. Koreans place a high value on minimizing waiting time and getting things done quickly in everyday life. Restaurants serve food fast, and cafés let you order in seconds through kiosks or mobile apps. Public transit shows real-time arrival info so people can use their time efficiently, and delivery is so fast that clothes, groceries, or food ordered online can arrive the very next day. Banks and hospitals use number tickets and automated systems to cut down unnecessary waiting — altogether, pali-pali culture captures how Koreans value saving time and getting what they need, fast.',
      photo: '/uploads/culture/culture-10.jpg',
      by: 'by. Si-won Song',
      photoSource: 'Personal screenshot',
    },
    {
      title: 'Hanok',
      desc: 'Hanok is Korea\'s traditional residential architecture, shaped by the country\'s climate and way of life. Built mainly from wood, clay, stone, and hanji (traditional paper), its two signature structures are ondol and maru. Ondol channels heat from a furnace under the floor to warm the room, ideal for cold winters, while maru is a raised wooden-floor space open to the breeze, used mainly in summer. Roofs are usually tiled, with eaves that project outward to control how much sunlight enters depending on the season, and hanji-covered windows let light in while still allowing air to pass through. Through this design, hanok lets residents heat with ondol in winter and cool through the maru\'s ventilation in summer — adapting the indoor environment to the season.',
      photo: '/uploads/culture/culture-11.jpg',
      by: 'by. Gyeong-been Lim',
      contentSource: 'Ministry of the Interior and Safety, National Archives of Korea; Korea Institute of Registered Architects News, "[2021 Hanok Policy Review ③] Hanok Policy: The Next 10 Years"',
      photoSource: 'Ministry of the Interior and Safety, National Archives of Korea; Korea Institute of Registered Architects News, "[2021 Hanok Policy Review ③] Hanok Policy: The Next 10 Years"',
      exploreLink: 'https://hanok.seoul.go.kr/front/kor/info/infoHanok.do?tab=2 (Hanok structure)',
    },
    {
      title: 'Korean Bathhouse & Sauna (Jjimjilbang) Culture',
      desc: "If you want to melt away fatigue from travel or daily life, nothing beats a Korean bathhouse (mokyoktang) and sauna complex (jjimjilbang). More than just a place to wash up, it's a quintessential Korean wellness retreat. Because the hot and cold baths are shared communal spaces, showering thoroughly before soaking is essential, and long hair should be tied up or wrapped so it doesn't touch the shared bathwater. Sweat it out in themed rooms — hot red clay or mineral salt saunas, then an ice-cold room for an instant cooldown — and try the iconic combo of ice-cold sikhye (sweet rice punch) with slow-baked sauna eggs. Even rolling a towel into the classic 'sheep-head' shape has become a fun cultural photo moment. Jjimjilbang is a place that unwinds both body and mind, and one of Korea's most beloved ways to relax.",
      photo: '/uploads/culture/culture-12.jpg',
      by: 'by. Seo-jin Baek',
      contentSource: 'Enkostay blog. (2026.06.29). "How to Use a Korean Bathhouse: A Complete Guide to Your First Jjimjilbang Visit." https://stay.enko.kr/blog/ko/',
      photoSource: 'Enkostay blog. (2026.06.29). "How to Use a Korean Bathhouse: A Complete Guide to Your First Jjimjilbang Visit." https://stay.enko.kr/blog/ko/',
    },
    {
      title: 'Gotgam (Dried Persimmon)',
      desc: "Gotgam is Korea's signature dried fruit, made by peeling persimmons and hanging them to dry slowly in a well-ventilated, sunlit spot. Through drying, the persimmon's natural astringency fades away while its sweetness intensifies, leaving a chewy skin around a soft, tender center. It was once a prized winter snack and one of the traditional \"three-colored fruits\" placed on tables for ancestral rites and holidays. Rich in vitamins A and C, it's said to help boost immunity and prevent colds, and in traditional Korean medicine it's also credited with soothing sore throats and easing hangovers. Recently it's been reinvented into modern desserts like gotgam rolls filled with walnuts or cheese, turning it into a premium K-food loved across generations.",
      photo: '/uploads/culture/culture-13.jpg',
      by: 'by. Su-A Choi',
      contentSource: 'Rural Development Administration. (2023.11.15). "Korean Agri-Food Information: The Benefits and History of Gotgam." Nongsaro. https://www.nongsaro.go.kr (accessed 2026.08.14)',
      photoSource: 'Naewon. (2026.05.22). "Chewy Snack: Sangju Gotgam." Naver Blog. https://m.blog.naver.com/wntlr6012/224293796772 (accessed 2026.08.14)',
    },
    {
      title: 'K-Delivery Culture',
      desc: "Korea's delivery culture has grown into something globally unique, shaped by the country's love of speed and convenience. A few taps on a smartphone app can bring anything from hot food to daily necessities straight to your door in no time. Ordering fried chicken for delivery to a Han River park or other outdoor spot has become a must-try experience for locals and tourists alike. More recently, eco-friendlier practices like reusable containers have started entering the industry as it matures. Beyond simple food delivery, this industry represents a defining piece of modern Korean life, blending exceptional IT infrastructure with everyday convenience.",
      photo: '/uploads/culture/culture-14.jpg',
      by: 'by. Su-been Wang',
      contentSource: 'Korea Tourism Organization. (2026). "Experiencing Korea\'s Delivery Culture." Visit Korea. https://korean.visitkorea.or.kr/ (accessed 2026.08.21)',
      photoSource: 'Korea Tourism Organization. (2026). "Delivery Food at Han River Park."',
      exploreLink: 'https://korean.visitkorea.or.kr/ (Visit Korea)',
    },
    {
      title: 'Dokdo',
      desc: 'Dokdo is Korean territory at the easternmost edge of the East Sea, about 87.4 km southeast of Ulleungdo. It consists of two main islets, Dongdo and Seodo, along with numerous smaller surrounding rocks, covering roughly 187,554㎡ in total, and administratively belongs to Dokdo-ri, Ulleung-eup, Ulleung-gun, Gyeongsangbuk-do. In 1900, Emperor Gojong of the Korean Empire issued Imperial Ordinance No. 41, formally placing Dokdo under Ulleung-gun\'s jurisdiction. Home to a rich variety of marine life and migratory birds, Dokdo is designated as Natural Monument No. 336 and protected as an ecological treasure — regarded as a precious symbol of Korea\'s nature, history, and sovereignty.',
      photo: '/uploads/culture/culture-15.jpg',
      by: 'by. So-jeong Kim',
      contentSource: 'Wikimedia Commons, Category:Liancourt Rocks. https://commons.wikimedia.org/wiki/Category:Liancourt_Rocks (accessed 2026.08.20)',
      photoSource: 'Wikimedia Commons, Category:Liancourt Rocks. https://commons.wikimedia.org/wiki/Category:Liancourt_Rocks (accessed 2026.08.20)',
      exploreLink: 'Ministry of Foreign Affairs Dokdo website: https://dokdo.mofa.go.kr/eng/',
    },
    {
      title: 'Baseball Cheering Culture',
      desc: "Korean baseball stadiums are more than a place to watch a game — they're a shared space where fans cheer and celebrate together. Every KBO team has its own cheer songs and chants, and fans sing along while calling out their favorite players' names. A cheer leader and cheerleaders lead the crowd from the field, and spectators clap and dance along in sync. Thousands of fans dancing together in time with the cheer songs is a sight unique to Korea, and fans wear their team's colors and wave cheering tools to show their passion. Korean baseball cheering culture is less about simply watching a game and more like a festival where everyone joins in and has fun together.",
      photo: '/uploads/culture/culture-16.jpg',
      by: 'by. Yeon-ji Jo',
      contentSource: 'Ju Hyun-hee, reporter. (2023.10.22). "Landers cheer flags filling the stands." Sports Dong-A. https://naver.me/lGsQxidS',
      photoSource: 'Ju Hyun-hee, reporter. (2023.10.22). "Landers cheer flags filling the stands." Sports Dong-A. https://naver.me/lGsQxidS',
    },
    {
      title: 'Najeon Chilgi (Mother-of-Pearl Lacquerware)',
      desc: 'Jagae is a traditional Korean craft material made by thinly processing the inner shell of abalone, conch, and pearl oysters — its signature trait is shimmering in different colors depending on the angle of light. It has long been used to decorate furniture, boxes, and small tables, and craftsmanship using it flourished from the Goryeo dynasty onward. Pieces of shell are cut into shapes like flowers, leaves, and birds, attached to a wooden base, and finished with lacquer to create najeon chilgi (mother-of-pearl lacquerware). Once used mainly to adorn furniture and household items for royalty and the upper class, today its traditional beauty has been reinterpreted for modern items like phone cases, jewelry boxes, and interior decor.',
      photo: '/uploads/culture/culture-17.jpg',
      by: 'by. Ye-eun Kim',
      contentSource: 'Academy of Korean Studies, Encyclopedia of Korean Culture, entry "Najeon Chilgi." https://encykorea.aks.ac.kr/Article/E0011448',
      photoSource: '"Lacquered box with mother-of-pearl inlay of lotus and peony arabesque," National Museum of Korea. https://www.museum.go.kr/MUSEUM/contents/M0502000000.do?schM=view&searchId=search&relicId=1338',
      exploreLink: 'Seoul Intangible Cultural Heritage — lacquer artisan Son Dae-hyeon making najeon chilgi. https://youtu.be/srHROM_qI9Q',
    },
    {
      title: 'Jjimjilbang Culture',
      desc: "Korea's jjimjilbang is a distinctive culture where bathing and relaxation come together in one place. You can sweat it out in several kinds of heated sauna rooms, then unwind in a comfortable lounge area. People often visit with friends or family to chat and spend time together, and enjoy signature snacks like sikhye and boiled eggs along the way. Many jjimjilbang operate 24 hours, so people also use them as a place to sleep or rest during a trip. More than just a bathhouse, jjimjilbang is a space where you can experience how Koreans relax and spend their leisure time.",
      photo: '/uploads/culture/culture-18.jpg',
      by: 'by. Si-won Song',
      contentSource: 'Personal photograph',
      photoSource: 'Personal photograph',
      exploreLink: 'https://ichpedia.org/ich/detail?id=43418',
    },
    {
      title: 'Dancheong',
      desc: 'Dancheong refers to the practice of painting the walls, pillars, and ceilings of traditional buildings in a range of colors and patterns — or to those patterns themselves, and to fine colors in general. It carries a dual purpose: elevating the dignity of wooden architecture through decorative solemnity, and practically protecting and extending the life of the wood against insects and moisture. It also carries religious and ceremonial meaning, marking a building as set apart from ordinary structures — which is why it appears most often on palaces and temples.',
      photo: '/uploads/culture/culture-19.jpg',
      by: 'by. Ju-hyun Kwak',
      contentSource: 'Academy of Korean Studies, Encyclopedia of Local Culture. Written by Jo Chun-yong, entry "Dancheong Master." https://www.grandculture.net/cheongju/dir/GC00202036 (accessed 2026.08.21)',
      photoSource: 'Korea Heritage Service. "Dragon-head dancheong on an upper pillar, Dancheong Master." Korea Heritage Portal. https://www.heritage.go.kr/heri/cul/culSelectDetail.do?ccbaKdcd=17&ccbaAsno=0000480000000&ccbaCtcd=38&pageNo=1_1_1_0 (accessed 2026.08.21)',
      exploreLink: 'https://royal.khs.go.kr/ROYAL/contents/R403000000.do?schM=view&id=20080501122000000045',
    },
    {
      title: 'Korean Address Culture',
      desc: 'Korean address culture is a language for expressing both "respect" and "closeness" between people. Which term you use for someone depends on age, relationship, social standing, and how close you are. Among close friends, it\'s common to call an older person "hyeong," "noona," "eonni," or "oppa" — even with no blood relation — to express family-like warmth. In formal settings, by contrast, people use role-based titles like "seonsaeng-nim" (teacher), "sajang-nim" (boss), or "gisa-nim" (driver) to show respect. In this way, how you address someone becomes a cultural expression of your relationship with them — a window into the Korean value of showing respect while also welcoming people close, almost like family.',
      photo: '/uploads/culture/culture-20.jpg',
      by: 'by. Bo-seong Kwon',
      contentSource: 'National Institute of Korean Language. "Standard Language Etiquette — Forms of Address in Society."',
      photoSource: 'AI-generated image (no original source given)',
      exploreLink: 'Standard Language Etiquette — Forms of Address in Society (National Institute of Korean Language)',
    },
    {
      title: 'Korean Traditional Food',
      desc: 'Korean traditional cuisine draws a clear line between the staple (rice) and side dishes, with everything served together on one table. Regional and seasonal ingredients shaped a rich variety of dishes, and because so many dishes are soup- or broth-based, both spoon and chopsticks are used together. A base of grains paired with vegetable, meat, and fish side dishes creates a nutritionally balanced meal, typically cooked with little oil through grilling, steaming, blanching, or seasoning raw — keeping it low in calories. Following the idea that food and medicine share the same root, pungent seasonings like scallion, garlic, and ginger are used generously, doubling as remedies that protect the body. Fermented foods are also a defining strength of Korean traditional cuisine.',
      photo: '/uploads/culture/culture-21.jpg',
      by: 'by. Eun-woo Park',
      contentSource: 'Kim Hyeon-cheol (history teacher, Seoul Yeongdong High School). (2024.10.01). "[Newspaper as Teacher] Bibimbap, Our Traditional Dish, Was Once a Royal Court Meal Served to the King\'s Relatives in Joseon." Chosun Ilbo. https://www.chosun.com/national/nie/2024/10/01/P52BMQFKQFFUDMIBSZQFWM7RVM/',
      photoSource: 'Ulsan Metropolitan Office of Education. https://school.use.go.kr/_cmm/fileDownload/yh-e/M01040903/10576dc097be65dd41afc32455cb54d5',
    },
    {
      title: 'Yugwa',
      desc: 'Yugwa is one of Korea\'s signature traditional confections, made from glutinous rice flour kneaded with alcohol and water, steamed and dried, deep-fried, then coated in rice syrup and a fine topping. Frying the dough forms countless tiny air pockets inside, giving yugwa its distinctive texture — crisp on the outside, melting soft within. The surface is coated with rice flour, puffed rice, or sesame for extra flavor, sometimes tinted with natural ingredients for color. In the Joseon dynasty, it was a top-tier delicacy served at royal banquets, noble family celebrations, and weddings, and today it remains a popular holiday gift and a modern K-dessert.',
      photo: '/uploads/culture/culture-22.jpg',
      by: 'by. Su-A Choi',
      contentSource: 'Korean Food Promotion Institute. (2024.01.20). "Traditional Korean Confections: The Making and Character of Yugwa." https://www.hansik.or.kr (accessed 2026.08.14)',
      photoSource: 'Saimdang. (2025.04.15). "[Glutinous Rice Yugwa] Crispy Outside, Melting Inside!" Naver Blog. https://m.blog.naver.com/saimdangfood/223833662867 (accessed 2026.08.14)',
    },
  ],
  ar: [
    {
      title: 'الهانغل',
      desc: 'الهانغل هو أبجدية ابتكرها الملك سيجونغ العظيم، رابع ملوك مملكة جوسون، من أجل شعبه عام 1443. إنها الأبجدية الوحيدة في العالم التي يُعرف مبتكرها وسنة ابتكارها ومبادئ تصميمها بدقة تامة، وتحظى بتقدير واسع لبنيتها العلمية. صُممت الحروف الساكنة على شكل أعضاء النطق التي تُلفظ بها، بينما تجمع الحروف المتحركة بين مبادئ السماء والأرض والإنسان لتشكيل عدد كبير من الأصوات. وفي عام 1997، أُدرج كتاب "هونمينجونغئوم هيريه" الذي يشرح مبادئ الهانغل ضمن سجل ذاكرة العالم لليونسكو. وحتى اليوم، تُعتبر الهانغل من أنسب الأبجديات لعصر المعلومات، وتؤدي دورًا محوريًا في الثقافة الكورية.',
      photo: '/uploads/culture/culture-01.jpg',
      by: 'by. Su-been Wang',
      contentSource: 'المتحف الوطني للهانغل. (2026). «تاريخ الهانغل». https://www.hangeul.go.kr/ (تاريخ الاطلاع: 2026.08.21)',
      photoSource: 'المتحف الوطني للهانغل. (2026). «هونمينجونغئوم هيريه».',
      exploreLink: 'https://www.hangeul.go.kr/ (المتحف الوطني للهانغل)',
    },
    {
      title: 'امتحان سونونغ',
      desc: 'سونونغ هو اختصار لاختبار القدرة الدراسية الجامعية، وهو الاختبار الذي يقيّم مدى استعداد الطلاب للدراسة الجامعية. يُعقد مرة واحدة فقط في السنة، في منتصف نوفمبر تقريبًا. تُستخدم نتيجته للقبول الجامعي، خصوصًا في مسارات القبول العادي والمبكر. تشمل مواد الاختبار: اللغة الكورية، والرياضيات، واللغة الإنجليزية، والتاريخ الكوري، والدراسات الاجتماعية، والعلوم، والدراسات المهنية، ولغة أجنبية ثانية أو الأحرف الصينية، ويختلف عدد المواد المطلوبة من طالب إلى آخر. يُصنَّف سونونغ وفق نظام تقييم نسبي من 9 مستويات وليس بنظام النجاح أو الرسوب، حيث يكون المستوى الأول هو الأعلى.',
      photo: '/uploads/culture/culture-02.jpg',
      by: 'by. Ju-hyun Kwak',
      photoSource: 'المعهد الكوري لتقييم المناهج الدراسية. https://www.kice.re.kr/main.do?s=kice (تاريخ الاطلاع: 2026.08.21)',
      contentSource: 'كُتب بناءً على تجربة شخصية كطالب في الصف الثالث الثانوي في كوريا حاليًا. (بحسب Ju-hyun Kwak)',
    },
    {
      title: 'الهانبوك',
      desc: 'الهانبوك هو الزي التقليدي الكوري الذي تطور عبر تاريخ طويل. يمكن رؤية أشكاله المبكرة في جداريات مقابر مملكة غوغوريو وتماثيل مملكة سيلا الطينية، وترسخت خلال عصر الممالك الثلاث بنيته الأساسية المعروفة اليوم: الجيوغوري (السترة) مع التشيما (التنورة) أو الباجي (السروال). يُصنع فضفاضًا وليس ضيقًا، مما يجعله مريحًا، ويجمع بين الخطوط المستقيمة والمنحنية ليمنح مظهرًا أنيقًا ومهيبًا. اختلفت الأقمشة والألوان في الماضي بحسب الطبقة الاجتماعية والموسم والمناسبة، أما اليوم فيُرتدى الهانبوك بشكل رئيسي في الأعياد والمناسبات الرسمية. وقد أصبح "الهانبوك اليومي" و"الهانبوك المطوّر" - وهما نسخ عملية حديثة من الطراز التقليدي - جزءًا من أزياء الشباب اليومية، كما لفتت موجة الكيبوب والدراما الكورية الأنظار العالمية إلى جمال الهانبوك.',
      photo: '/uploads/culture/culture-03.jpg',
      by: 'by. Ye-eun Kim',
      contentSource: 'الأكاديمية الكورية للدراسات، الموسوعة الوطنية للثقافة الكورية، مدخل «الهانبوك». https://encykorea.aks.ac.kr/Article/E0061645',
      photoSource: 'وزارة التعليم، المعهد الوطني للتربية الخاصة. (2020). «فهم حكمة الأجداد في الهانبوك». https://www.nise.go.kr/sedu/2020/sw_p/pr2/pr1_2/page02.html',
      exploreLink: 'المتحف الوطني الفولكلوري الكوري - صندوق ثقافة "الهانبوك". https://www.nfm.go.kr/k-box/ui/hanbok/introduce.do',
    },
    {
      title: 'الكيبوب (K-pop)',
      desc: 'الكيبوب هو نوع من الموسيقى الشعبية نشأ في كوريا وأصبح محبوبًا في جميع أنحاء العالم، ويتميز بألحان "hook" جذابة ورقصات جماعية مبهرة. مهّد فوز فرقتي BoA وTVXQ بصدارة قائمة Oricon اليابانية عام 2005 الطريق الأول نحو الخارج، ثم جاء وصول أغنية "Gangnam Style" لسايكو إلى المركز الثاني في قائمة Billboard Hot 100 عام 2012 ليُعرّف السوق الأمريكية بالكيبوب رسميًا. بعدها رفعت فرقة BTS مكانة الكيبوب عالميًا بتصدرها قائمة Billboard Hot 100 عدة مرات، وتحظى اليوم فرق مثل BLACKPINK وStray Kids وTWICE وNewJeans بشعبية كبيرة في الخارج. تدرّب شركات الترفيه المتدربين لسنوات طويلة على الغناء والرقص واللغات لتقديم عروض عالية الجودة، وتوسّع الكيبوب اليوم ليتجاوز الموسيقى إلى الأفلام والرسوم المتحركة، مما دفع المعجبين حول العالم لتعلم اللغة الكورية والاهتمام بالطعام والدراما الكورية ضمن موجة الهاليو (Hallyu) الأوسع.',
      photo: '/uploads/culture/culture-04.jpg',
      by: 'by. So-jeong Kim',
      contentSource: 'الموسوعة الوطنية للثقافة الكورية، مدخل «الكيبوب». https://encykorea.aks.ac.kr/Article/E0073667',
      photoSource: 'صورة التقطها مقدّم المحتوى في حفل حي (لم يُذكر مصدر إضافي)',
      exploreLink: 'الموسوعة الوطنية للثقافة الكورية، مدخل «الكيبوب». https://encykorea.aks.ac.kr/Article/E0073667',
    },
    {
      title: 'التايكوندو',
      desc: 'التايكوندو رياضة قتالية تهدف إلى الدفاع عن النفس وتحقيق الذات، وتتخصص في تقنيات الدفاع والهجوم بالأيدي العارية مع التركيز على الرَّكْل. تترجم "المبادئ الخمسة" للتايكوندو مُثُلَ ضبط النفس وخدمة الصالح العام إلى سلوك يومي عملي، وهي: الصبر، والشجاعة، والأدب، والعدالة، وضبط النفس (وتُذكر أحيانًا مع الخدمة). أصبح التايكوندو رياضة أولمبية رسمية تجمع رياضيين من مختلف أنحاء العالم للتنافس، ويقف اليوم كفن قتالي كوري تقليدي ورياضة عالمية حديثة يحظى بمحبة واسعة داخل كوريا وخارجها.',
      photo: '/uploads/culture/culture-05.jpg',
      by: 'by. Eun-woo Park',
      photoSource: 'الموقع الرسمي للأولمبياد. مارتا مارتين. (2022.06.22). «فئات الوزن في تايكوندو باريس 2024». https://www.olympics.com/en/news/paris-2024-weight-categories-for-olympic-taekwondo',
      contentSource: 'الموقع الرسمي للكوكيوون (المقر العالمي للتايكوندو). https://www.kukkiwon.or.kr',
      exploreLink: 'https://www.kukkiwon.or.kr/base/board/list?boardManagementNo=37&menuLevel=3&menuNo=62',
    },
    {
      title: 'ثقافة تشجيع الامتحانات',
      desc: 'في كوريا، من الشائع إهداء شخص مقبل على امتحان مهم قطعة من الـ"يوت" (حلوى لزجة) أو "تشابسالتوك" (كعك الأرز الحلو) تمنيًا له بالنجاح. ولأن كلا الحلويين لزجان ويلتصقان بسهولة، يحمل هذا الإهداء معنى "الالتصاق" بالنجاح وتحقيق النتيجة المرجوة. غالبًا ما يقدّم الأهل والأصدقاء والمعلمون هذه الحلويات للطلاب قبل امتحان السونونغ أو غيره من الامتحانات المهمة كطريقة لإظهار الدعم، بل يُقال إن السكر الطبيعي في اليوت يتحلل بسرعة كافية ليمنح الدماغ دفعة طاقة سريعة. إنها طريقة كورية مميزة للتشجيع، تُضفي على طعام يومي بسيط معنى الأمل والدعم.',
      photo: '/uploads/culture/culture-06.jpg',
      by: 'by. Bo-seong Kwon',
      contentSource: 'https://www.thinkfood.co.kr/news/articleView.html?idxno=90269',
      photoSource: 'صحيفة Gyeongin Ilbo؛ ناموويكي',
      exploreLink: 'https://www.nongmin.com/article/20141108269230',
    },
    {
      title: 'خزف غوريو الأخضر (Celadon)',
      desc: 'خزف غوريو الأخضر هو الفخار المميز لعصر مملكة غوريو، وقد بلغ ذروته التقنية في القرنين الثاني عشر والثالث عشر. تتمثل سمته المميزة في طلاء أزرق مخضر يُعرف عادة باسم "بيساك" (لون اليشم). أما أشهر تقنياته الزخرفية فهي تقنية "سانغغام" الحفرية، حيث يُحفر النقش على سطح الخزف ثم يُملأ بطين مختلف اللون، ويُطلى ويُحرق لإظهار الزخرفة. تنوعت الزخارف بين زهور اللوتس والأقحوان والغيوم وطيور الكركي والأسماك؛ وبينما تأثرت القطع المبكرة بالتقنية الصينية، طوّر حرفيو غوريو تدريجيًا أشكالهم وألوانهم الخاصة. صُنع هذا الخزف للاستخدام اليومي والطقوس والزينة على حد سواء، وهو إرث ثقافي مهم يعكس مستوى الحرفية في عصره.',
      photo: '/uploads/culture/culture-07.jpg',
      by: 'by. Gyeong-been Lim',
      contentSource: 'ناموويكي؛ بوابة الثقافة التقليدية الكورية',
      photoSource: 'ناموويكي؛ بوابة الثقافة التقليدية الكورية',
      exploreLink: 'https://www.khs.go.kr (هيئة التراث الكورية)',
    },
    {
      title: 'وجبات الغداء المدرسية الكورية',
      desc: 'يحصل كل طالب في كوريا على وجبة متوازنة طازجة على صينية فولاذية مقسّمة إلى أقسام. يتكون أساس الوجبة من الأرز والحساء، إلى جانب طبق رئيسي مثل البولغوغي أو التونكاتسو أو السمك المشوي، وأطباق جانبية من الخضار والبيض، وطبق الكيمتشي الذي لا يغيب أبدًا. يشرف اختصاصيو تغذية معتمدون وطاقم مطبخ داخل المدرسة على حساب السعرات الحرارية والصوديوم والعناصر الغذائية باستخدام مكونات طازجة، على عكس المدارس التي تعتمد على وجبات معلبة أو جاهزة. كما تنظّم المقاصف أيامًا لقوائم خاصة، من الأطباق الرائجة مثل التوكبوكي بصلصة الروزيه أو البيتزا بقشرة الجبن، إلى أيام المطبخ العالمي بالتاكو أو الفو، وحلويات تشجيعية مثل كعك الأرز في موسم الامتحانات.',
      photo: '/uploads/culture/culture-08.jpg',
      by: 'by. Seo-jin Baek',
      contentSource: 'AI',
      photoSource: 'AI',
    },
    {
      title: 'الكيمتشي',
      desc: 'الكيمتشي طبق كوري تقليدي يُصنع بتخمير خضروات مثل الملفوف الصيني أو الفجل مع توابل كالفلفل الأحمر المطحون والثوم والزنجبيل. يظهر الكيمتشي على المائدة الكورية شبه يوميًا، بأصناف إقليمية وموسمية لا حصر لها. يمنحه التخمير نكهة عميقة مميزة، ولتحضير مؤونة الشتاء، تجتمع العائلات والجيران تقليديًا لتحضير كميات كبيرة منه معًا في طقس يُعرف باسم "كيمجانغ". يعكس الكيمجانغ الثقافة المجتمعية الكورية بامتياز، وقد أُدرج تقليد صناعة الكيمتشي ومشاركته ضمن قائمة اليونسكو التمثيلية للتراث الثقافي غير المادي للإنسانية عام 2013.',
      photo: '/uploads/culture/culture-09.jpg',
      by: 'by. Yeon-ji Jo',
      contentSource: 'الصحفي غونغ جونغ-سيك. (2026.08.20). «فعالية "كيمتشي المحبة" في جامعة يونغنام». https://naver.me/5yhoOkCK',
      photoSource: 'الصحفي غونغ جونغ-سيك. (2026.08.20). «فعالية "كيمتشي المحبة" في جامعة يونغنام». https://naver.me/5yhoOkCK',
    },
    {
      title: 'ثقافة "بالي بالي" (بسرعة بسرعة)',
      desc: 'تمتلك كوريا ثقافة مميزة تُعرف باسم "بالي بالي" أي "بسرعة، بسرعة". يُولي الكوريون أهمية كبيرة لتقليل وقت الانتظار وإنجاز الأمور بسرعة في حياتهم اليومية. تُقدَّم الأطعمة بسرعة في المطاعم، وتتيح المقاهي الطلب خلال ثوانٍ عبر أجهزة الطلب الذاتي أو التطبيقات. تعرض وسائل النقل العام معلومات الوصول اللحظية لاستغلال الوقت بكفاءة، كما تطوّر التوصيل السريع لدرجة أن الملابس أو المستلزمات أو الطعام المطلوب عبر الإنترنت يصل في اليوم التالي مباشرة. تستخدم البنوك والمستشفيات أنظمة الأرقام والأتمتة لتقليل الانتظار غير الضروري - وباختصار، تعكس ثقافة "بالي بالي" حرص الكوريين على توفير الوقت والحصول على ما يريدونه بسرعة.',
      photo: '/uploads/culture/culture-10.jpg',
      by: 'by. Si-won Song',
      photoSource: 'لقطة شاشة شخصية',
    },
    {
      title: 'الهانوك',
      desc: 'الهانوك هو العمارة السكنية التقليدية الكورية، التي تطورت لتلائم مناخ كوريا وأسلوب حياة سكانها. يُبنى غالبًا من الخشب والطين والحجر وورق الهانجي، وأبرز عنصرين معماريين فيه هما الأوندول والمارو. ينقل نظام الأوندول الحرارة من موقد أسفل الأرضية لتدفئة الغرفة، وهو مثالي في الشتاء البارد، بينما المارو هو أرضية خشبية مرتفعة عن الأرض تسمح بمرور الهواء، وتُستخدم غالبًا في الصيف. عادة ما يكون السقف من القرميد، مع أفاريز بارزة تتحكم بكمية ضوء الشمس الداخل حسب الفصل، وتُغطى النوافذ بورق الهانجي الذي يسمح بدخول الضوء مع مرور الهواء في الوقت نفسه. بهذا التصميم، يتيح الهانوك التدفئة بالأوندول شتاءً والتبريد عبر تهوية المارو صيفًا، متكيفًا مع الفصول.',
      photo: '/uploads/culture/culture-11.jpg',
      by: 'by. Gyeong-been Lim',
      contentSource: 'وزارة الداخلية والسلامة، الأرشيف الوطني الكوري؛ صحيفة نقابة المهندسين المعماريين الكوريين، «[مراجعة سياسة الهانوك 2021 ③] سياسة الهانوك: السنوات العشر القادمة»',
      photoSource: 'وزارة الداخلية والسلامة، الأرشيف الوطني الكوري؛ صحيفة نقابة المهندسين المعماريين الكوريين، «[مراجعة سياسة الهانوك 2021 ③] سياسة الهانوك: السنوات العشر القادمة»',
      exploreLink: 'https://hanok.seoul.go.kr/front/kor/info/infoHanok.do?tab=2 (بنية الهانوك)',
    },
    {
      title: 'ثقافة الحمامات والساونا الكورية (تشيمجيلبانغ)',
      desc: 'إذا كنت تريد التخلص من إرهاق السفر أو الحياة اليومية، فلا شيء يضاهي الحمام الكوري (موكيوكتانغ) ومجمع الساونا (تشيمجيلبانغ). فهو أكثر من مجرد مكان للاستحمام - إنه ملاذ استجمام كوري أصيل. ولأن الأحواض الساخنة والباردة مساحات مشتركة، فالاستحمام الكامل قبل النقع أمر أساسي، ويجب ربط الشعر الطويل أو لفه حتى لا يلامس ماء الحوض المشترك. تعرّق في غرف مواضيعية - الطين الأحمر الساخن أو غرف الملح المعدني، ثم انتقل إلى غرفة جليدية للتبريد الفوري - وجرّب المزيج الشهير من السيكهي المثلج (شراب الأرز الحلو) مع بيض الساونا المشوي ببطء. حتى لف منشفة على شكل "رأس الخروف" الشهير أصبح لحظة تصوير ثقافية ممتعة. التشيمجيلبانغ مكان يريح الجسد والعقل معًا، وأحد أكثر طرق الاسترخاء محبةً لدى الكوريين.',
      photo: '/uploads/culture/culture-12.jpg',
      by: 'by. Seo-jin Baek',
      contentSource: 'مدونة Enkostay. (2026.06.29). «كيفية استخدام الحمام الكوري: دليل شامل لأول زيارة إلى تشيمجيلبانغ». https://stay.enko.kr/blog/ko/',
      photoSource: 'مدونة Enkostay. (2026.06.29). «كيفية استخدام الحمام الكوري: دليل شامل لأول زيارة إلى تشيمجيلبانغ». https://stay.enko.kr/blog/ko/',
    },
    {
      title: 'غوتغام (الكاكي المجفف)',
      desc: 'غوتغام هو فاكهة كوريا التقليدية المجففة الأشهر، تُصنع بتقشير ثمار الكاكي وتعليقها لتجف ببطء في مكان مشمس وجيد التهوية. أثناء التجفيف، تختفي مرارة الكاكي الطبيعية تدريجيًا بينما تزداد حلاوته، ليصبح قوامه مطاطيًا من الخارج وطريًا من الداخل. كان في الماضي وجبة خفيفة ثمينة في الشتاء وأحد "الفواكه الثلاثية الألوان" التي تُوضع على موائد الطقوس والأعياد. وهو غني بفيتاميني A وC، ويُقال إنه يعزز المناعة ويقي من نزلات البرد، بل يُنسب إليه في الطب الكوري التقليدي تخفيف التهاب الحلق وتسكين آثار الثمالة. وحديثًا، أُعيد تقديمه بحلويات عصرية مثل لفائف الغوتغام المحشوة بالجوز أو الجبن، ليصبح طعامًا كوريًا فاخرًا محبوبًا لدى جميع الأجيال.',
      photo: '/uploads/culture/culture-13.jpg',
      by: 'by. Su-A Choi',
      contentSource: 'إدارة التنمية الريفية. (2023.11.15). «معلومات الأغذية الزراعية الكورية: فوائد وتاريخ الغوتغام». نونغسارو. https://www.nongsaro.go.kr (تاريخ الاطلاع: 2026.08.14)',
      photoSource: 'نايوون. (2026.05.22). «وجبة خفيفة مطاطية: غوتغام سانغجو». مدونة نيفر. https://m.blog.naver.com/wntlr6012/224293796772 (تاريخ الاطلاع: 2026.08.14)',
    },
    {
      title: 'ثقافة التوصيل الكورية',
      desc: 'تطورت ثقافة التوصيل الكورية لتصبح فريدة عالميًا، بفضل حب الكوريين للسرعة والراحة. تكفي بضع نقرات على تطبيق الهاتف لإيصال أي شيء، من الطعام الساخن إلى المستلزمات اليومية، مباشرة إلى الباب بسرعة. كما أصبح طلب الدجاج المقلي للتوصيل إلى حديقة نهر الهان أو أي مكان خارجي تجربة لا بد منها للسكان المحليين والسياح على حد سواء. ومؤخرًا، بدأت ممارسات صديقة للبيئة مثل استخدام الأوعية القابلة لإعادة الاستخدام تدخل هذه الصناعة مع نضجها. وتمثل صناعة التوصيل هذه، إلى جانب كونها خدمة توصيل طعام بسيطة، جانبًا محوريًا من الحياة الكورية الحديثة يمزج بين بنية تحتية تقنية متطورة والحياة اليومية.',
      photo: '/uploads/culture/culture-14.jpg',
      by: 'by. Su-been Wang',
      contentSource: 'منظمة السياحة الكورية. (2026). «تجربة ثقافة التوصيل الكورية». Visit Korea. https://korean.visitkorea.or.kr/ (تاريخ الاطلاع: 2026.08.21)',
      photoSource: 'منظمة السياحة الكورية. (2026). «طعام التوصيل في حديقة نهر الهان».',
      exploreLink: 'https://korean.visitkorea.or.kr/ (Visit Korea)',
    },
    {
      title: 'دوكدو',
      desc: 'دوكدو أرض كورية تقع في أقصى شرق بحر الشرق (بحر اليابان)، على بعد نحو 87.4 كم جنوب شرق جزيرة أولونغدو. تتكون من جزيرتين رئيسيتين، دونغدو وسيودو، إلى جانب العديد من الصخور المحيطة الصغيرة، بمساحة إجمالية تبلغ نحو 187,554 مترًا مربعًا، وتتبع إداريًا لمنطقة دوكدو-ري في أولونغ-إيوب، مقاطعة أولونغ-غون، محافظة غيونغسانغبوك-دو. في عام 1900، أصدر الإمبراطور غوجونغ من الإمبراطورية الكورية المرسوم الإمبراطوري رقم 41، الذي وضع دوكدو رسميًا تحت ولاية أولونغ-غون. تُعد دوكدو موطنًا لتنوع غني من الكائنات البحرية والطيور المهاجرة، وهي مصنّفة كأثر طبيعي رقم 336 وتحظى بحماية بيئية خاصة - وتُعتبر رمزًا ثمينًا لطبيعة كوريا وتاريخها وسيادتها.',
      photo: '/uploads/culture/culture-15.jpg',
      by: 'by. So-jeong Kim',
      contentSource: 'ويكيميديا كومنز، تصنيف: Liancourt Rocks. https://commons.wikimedia.org/wiki/Category:Liancourt_Rocks (تاريخ الاطلاع: 2026.08.20)',
      photoSource: 'ويكيميديا كومنز، تصنيف: Liancourt Rocks. https://commons.wikimedia.org/wiki/Category:Liancourt_Rocks (تاريخ الاطلاع: 2026.08.20)',
      exploreLink: 'موقع دوكدو التابع لوزارة الخارجية الكورية: https://dokdo.mofa.go.kr/eng/',
    },
    {
      title: 'ثقافة تشجيع البيسبول',
      desc: 'ملاعب البيسبول الكورية أكثر من مجرد مكان لمشاهدة المباراة - إنها مساحة مشتركة يجتمع فيها المشجعون للتشجيع والاستمتاع معًا. لكل فريق في الدوري الكوري المحترف أغانيه وهتافاته الخاصة، ويردد المشجعون أسماء لاعبيهم المفضلين وهم يغنون معًا. يقود قائد التشجيع وفريق المشجعات الحشد من أرض الملعب، بينما يصفّق المتفرجون ويتحركون في تناغم. ومن أكثر المشاهد تميزًا في كوريا رؤية آلاف المشجعين يرقصون معًا في وقت واحد على وقع أغاني التشجيع، ويرتدي المشجعون ألوان فريقهم ويلوّحون بأدوات التشجيع تعبيرًا عن حماسهم. ثقافة تشجيع البيسبول الكورية أقرب إلى مهرجان جماعي منها إلى مجرد مشاهدة مباراة.',
      photo: '/uploads/culture/culture-16.jpg',
      by: 'by. Yeon-ji Jo',
      contentSource: 'الصحفية جو هيون-هي. (2023.10.22). «أعلام تشجيع فريق لاندرز تملأ المدرجات». سبورتس دونغ-آ. https://naver.me/lGsQxidS',
      photoSource: 'الصحفية جو هيون-هي. (2023.10.22). «أعلام تشجيع فريق لاندرز تملأ المدرجات». سبورتس دونغ-آ. https://naver.me/lGsQxidS',
    },
    {
      title: 'الصدف اللؤلؤي (نايجون تشيلغي)',
      desc: 'الجاغيه مادة حرفية كورية تقليدية تُصنع من الطبقة الداخلية الرقيقة لأصداف الأذن البحرية والحلزون واللؤلؤ، وأبرز ميزاته أنه يلمع بألوان مختلفة حسب زاوية الضوء. استُخدم منذ زمن بعيد لتزيين الأثاث والصناديق والطاولات الصغيرة، وازدهرت الحرفية القائمة عليه منذ عصر مملكة غوريو. تُقص قطع الصدف على شكل زهور وأوراق وطيور، وتُلصق على قاعدة خشبية، ثم تُطلى بالورنيش لتشكيل حرفة "نايجون تشيلغي" (الصدف المطلي بالورنيش). وكان يُستخدم في السابق أساسًا لتزيين أثاث ومقتنيات العائلة المالكة والطبقة الراقية، أما اليوم فقد أُعيد تفسير جماله التقليدي بأسلوب حديث في أغطية الهواتف وصناديق المجوهرات وقطع الديكور.',
      photo: '/uploads/culture/culture-17.jpg',
      by: 'by. Ye-eun Kim',
      contentSource: 'الأكاديمية الكورية للدراسات، الموسوعة الوطنية للثقافة الكورية، مدخل «نايجون تشيلغي». https://encykorea.aks.ac.kr/Article/E0011448',
      photoSource: '«صندوق مطلي بالورنيش ومرصّع بالصدف بزخرفة اللوتس والفاوانيا»، المتحف الوطني الكوري. https://www.museum.go.kr/MUSEUM/contents/M0502000000.do?schM=view&searchId=search&relicId=1338',
      exploreLink: 'التراث غير المادي لمدينة سيول - الحرفي سون داي-هيون يصنع نايجون تشيلغي. https://youtu.be/srHROM_qI9Q',
    },
    {
      title: 'ثقافة التشيمجيلبانغ',
      desc: 'التشيمجيلبانغ الكوري ثقافة فريدة تجمع بين الاستحمام والاسترخاء في مكان واحد. يمكنك التعرّق في أنواع مختلفة من غرف الساونا الساخنة، ثم الاسترخاء في مساحة استراحة مريحة. كثيرًا ما يزور الناس هذه الأماكن مع الأصدقاء أو العائلة للدردشة وقضاء الوقت معًا، والاستمتاع بوجبات خفيفة مميزة مثل السيكهي والبيض المسلوق. وبما أن العديد منها يعمل على مدار 24 ساعة، يستخدمها البعض أيضًا للنوم أو الاستراحة أثناء السفر. التشيمجيلبانغ أكثر من مجرد حمام - إنه مكان يمكن من خلاله تجربة كيف يسترخي الكوريون ويقضون أوقات فراغهم.',
      photo: '/uploads/culture/culture-18.jpg',
      by: 'by. Si-won Song',
      contentSource: 'تصوير شخصي',
      photoSource: 'تصوير شخصي',
      exploreLink: 'https://ichpedia.org/ich/detail?id=43418',
    },
    {
      title: 'دانتشيونغ',
      desc: 'يشير مصطلح "دانتشيونغ" إلى رسم جدران وأعمدة وأسقف المباني التقليدية بألوان وزخارف متعددة، أو إلى تلك الزخارف نفسها، وكذلك إلى الألوان الجميلة بشكل عام. يحمل هذا الفن غرضًا مزدوجًا: رفع مكانة العمارة الخشبية عبر الزخرفة المهيبة، وحماية الخشب عمليًا من الحشرات والرطوبة لإطالة عمره. كما يحمل دلالة دينية وطقسية، إذ يميّز المبنى عن الإنشاءات العادية - ولهذا يظهر غالبًا في القصور والمعابد.',
      photo: '/uploads/culture/culture-19.jpg',
      by: 'by. Ju-hyun Kwak',
      contentSource: 'الأكاديمية الكورية للدراسات، الموسوعة الإلكترونية للثقافة المحلية. كتبها جو تشون-يونغ، مدخل «حرفي الدانتشيونغ». https://www.grandculture.net/cheongju/dir/GC00202036 (تاريخ الاطلاع: 2026.08.21)',
      photoSource: 'هيئة التراث الكورية. «زخرفة رأس التنين على عمود علوي، حرفي الدانتشيونغ». بوابة التراث الكوري. https://www.heritage.go.kr/heri/cul/culSelectDetail.do?ccbaKdcd=17&ccbaAsno=0000480000000&ccbaCtcd=38&pageNo=1_1_1_0 (تاريخ الاطلاع: 2026.08.21)',
      exploreLink: 'https://royal.khs.go.kr/ROYAL/contents/R403000000.do?schM=view&id=20080501122000000045',
    },
    {
      title: 'ثقافة الألقاب الكورية',
      desc: 'ثقافة الألقاب الكورية لغة تعبّر عن "الاحترام" و"القرب" بين الناس في آن واحد. يختلف اللقب المستخدم للشخص حسب العمر والعلاقة والمكانة الاجتماعية ودرجة الألفة. بين الأصدقاء المقربين، من الشائع أن يُنادى الشخص الأكبر سنًا بـ"هيونغ" أو "نونا" أو "أونّي" أو "أوبّا" حتى دون قرابة دم، تعبيرًا عن دفء أسري. أما في المواقف الرسمية، فيستخدم الناس ألقابًا مرتبطة بالدور مثل "سونسِنغ-نيم" (معلم) أو "ساجانغ-نيم" (مدير) أو "غيسا-نيم" (سائق) إظهارًا للاحترام. وهكذا تصبح طريقة مناداة الشخص تعبيرًا ثقافيًا عن العلاقة معه، ونافذة على قيمة كورية أساسية: احترام الآخر مع الترحيب به بقرب يشبه الأسرة أحيانًا.',
      photo: '/uploads/culture/culture-20.jpg',
      by: 'by. Bo-seong Kwon',
      contentSource: 'المعهد الوطني للغة الكورية. «آداب اللغة المعيارية - صيغ المناداة في المجتمع».',
      photoSource: 'صورة مولّدة بالذكاء الاصطناعي (لا يوجد مصدر أصلي مذكور)',
      exploreLink: 'آداب اللغة المعيارية - صيغ المناداة في المجتمع (المعهد الوطني للغة الكورية)',
    },
    {
      title: 'الطعام الكوري التقليدي',
      desc: 'يميّز المطبخ الكوري التقليدي الفصل الواضح بين الطبق الأساسي (الأرز) والأطباق الجانبية، مع تقديم كل شيء معًا على مائدة واحدة. أنتجت المكونات الإقليمية والموسمية تنوعًا غنيًا من الأطباق، ولأن الكثير منها قائم على الحساء أو المرق، يُستخدم الملعقة والعيدان معًا. يشكّل أساس الحبوب مع أطباق جانبية من الخضار واللحوم والأسماك وجبة متوازنة غذائيًا، وتُطهى عادة بقليل من الزيت عبر الشوي أو التبخير أو السلق أو التتبيل النيء، مما يجعلها منخفضة السعرات. وانطلاقًا من فكرة أن "الطعام والدواء من أصل واحد"، تُستخدم توابل نفّاذة كالبصل الأخضر والثوم والزنجبيل بكثرة، وهي في الوقت نفسه مكونات علاجية تحمي الجسم. كما تُعد الأطعمة المخمّرة إحدى أبرز سمات المطبخ الكوري التقليدي.',
      photo: '/uploads/culture/culture-21.jpg',
      by: 'by. Eun-woo Park',
      contentSource: 'كيم هيون-تشول (معلم تاريخ، ثانوية سيول يونغدونغ). (2024.10.01). «[الصحيفة كمعلم] البيبيمباب، طبقنا التقليدي، كان طعامًا ملكيًا يُقدَّم لأقارب الملك في عصر جوسون». تشوسون إيلبو. https://www.chosun.com/national/nie/2024/10/01/P52BMQFKQFFUDMIBSZQFWM7RVM/',
      photoSource: 'مكتب التعليم في مدينة أولسان. https://school.use.go.kr/_cmm/fileDownload/yh-e/M01040903/10576dc097be65dd41afc32455cb54d5',
    },
    {
      title: 'اليوغوا',
      desc: 'اليوغوا واحد من أشهر الحلويات الكورية التقليدية، يُصنع من دقيق الأرز اللزج المعجون بالكحول والماء، ثم يُبخّر ويُجفف ويُقلى، ويُغطى أخيرًا بشراب الأرز وطبقة خارجية ناعمة. أثناء قلي العجينة، تتشكل بداخلها عشرات الفقاعات الهوائية الدقيقة، مما يمنح اليوغوا قوامه المميز: مقرمش من الخارج وذائب طريّ من الداخل. تُغطى الطبقة الخارجية بدقيق الأرز أو الأرز المنفوش أو السمسم لمزيد من النكهة، وأحيانًا تُلوَّن بمكونات طبيعية. كان في عصر جوسون حلوى فاخرة لا تغيب عن ولائم القصر واحتفالات طبقة النبلاء وحفلات الزفاف، ولا يزال اليوم هدية شائعة في الأعياد وحلوى كورية حديثة محبوبة.',
      photo: '/uploads/culture/culture-22.jpg',
      by: 'by. Su-A Choi',
      contentSource: 'معهد ترويج الطعام الكوري. (2024.01.20). «الحلويات الكورية التقليدية: صناعة اليوغوا وخصائصه». https://www.hansik.or.kr (تاريخ الاطلاع: 2026.08.14)',
      photoSource: 'سايمدانغ. (2025.04.15). «[يوغوا الأرز اللزج] مقرمش وذائب في آن واحد!». مدونة نيفر. https://m.blog.naver.com/saimdangfood/223833662867 (تاريخ الاطلاع: 2026.08.14)',
    },
  ],
};
