import type { Lang } from '@/lib/i18n';

export interface MemberBio {
  position?: string;
  age?: string;
  mbti?: string;
  interests?: string;
  skill?: string;
  food?: string;
  color?: string;
  music?: string;
  dream?: string;
  motto?: string;
  instagram?: string;
  phone?: string;
}

// Free-text answers from the team roster form, kept per-language (ko: as submitted,
// en/ar: translated). Fields left blank on the form are simply omitted here so the
// detail view can skip rendering that row entirely. Phone numbers are partially
// masked (last two digits of each group hidden) since these profiles are public.
export const TEAM_BIOS: Record<Lang, Record<number, MemberBio>> = {
  ko: {
    1: {
      position: '부대표',
      age: '19',
      mbti: 'ENTJ',
      interests: 'AI, 디자인, 경제, 경영, 무언가 만들어 내는 것',
      skill: '무언가 만들어 내는 것',
      food: '애호박전, 마라탕, 떡볶이, 매운 음식 등',
      color: '무채색',
      music: '시가 될 이야기 / 신지훈 / 발라드',
      dream: '경제, SCM, 위기 관리 분야의 전문가',
      motto: "DON'T COMPROMISE WITH MY SELF",
      instagram: '@hyum35',
      phone: '010-53XX-29XX',
    },
    2: {
      position: '서기',
      age: '18',
      mbti: 'INTJ',
      interests: '언어와 문화, 여행',
      skill: '외국어',
      food: '수박',
      color: '갈색',
      music: '힙합, 얼터너티브',
      dream: '성공하기',
      motto: '안 되면 되게 하라!',
      instagram: '@bojoegm',
      phone: '010-46XX-74XX',
    },
    3: {
      position: '홍보담당',
      age: '17',
      mbti: 'ISTJ',
      interests: '패션',
      skill: '스케이트',
      food: '수박',
      color: '핑크',
      music: 'Red Red · CORTIS · K-pop',
      dream: '패션모델',
      motto: '유행을 따르지 않고 나만의 기준을 세운다',
      instagram: 'yeonz._zo',
      phone: '010-88XX-84XX',
    },
    4: {
      position: '대표',
      age: '23',
      mbti: 'INFJ',
      interests: '건강한 삶 / 배움과 통찰',
      skill: '새로운 도전을 받아들이는 것',
      food: '비빔밥 · 샌드위치',
      color: '노랑',
      music: 'MIRACLE · NCT WISH · K-POP',
      dream: 'CEO / 베풀며 행복하게 살기',
      motto: '나만의 속도로 살자',
      instagram: '@tjwlss',
      phone: '010-56XX-85XX',
    },
    5: {
      position: '통역',
      age: '1994년생',
      interests: '여행, 고양이, 영화',
      dream: '아랍어 통역사',
      motto: '다정함 · 꼼꼼함 · 모험심',
      phone: '010-49XX-49XX',
    },
    6: {
      position: '토의활동 담당',
      age: '17',
      mbti: 'INTP',
      interests: '영화',
      skill: '발표',
      food: '떡볶이',
      color: '초록',
      music: '한국 레트로 음악',
      dream: '세계 일주하기',
      motto: '세상을 보라.',
      instagram: '@soxwe_',
      phone: '010-32XX-80XX',
    },
    7: {
      position: '문화발표 담당',
      age: '17',
      mbti: 'ESTP',
      interests: '운동',
      skill: '태권도',
      food: '햄버거',
      color: '핑크',
      music: '러브어택 · 리센느 · 발라드',
      dream: '경찰',
      motto: '한 걸음씩 꾸준히.',
      instagram: '@tkd_dmsdn',
      phone: '010-52XX-62XX',
    },
    8: {
      position: '서기',
      age: '18',
      mbti: 'INFP',
      interests: '독서, 수영, 자기계발, 글쓰기',
      skill: '글쓰기, 수영',
      food: '떡볶이, 피자',
      color: '옥색',
      instagram: '@subeen.09',
      phone: '010-67XX-69XX',
    },
    9: {
      position: '사진·영상 담당',
      age: '17',
      instagram: 'biinu.o',
      phone: '010-92XX-33XX',
    },
    10: {
      position: '사진·영상 담당',
      age: '17',
      mbti: 'ISTP',
      interests: '여행, 노래 듣기',
      color: '무채색',
      music: '힙합, 알앤비',
      dream: '100개국 여행하기',
      motto: '나는 천천히 걷지만 절대 뒤로 걷진 않는다',
      instagram: '@eeeeung_',
      phone: '010-58XX-07XX',
    },
    11: {
      position: '부대표',
      age: '17',
      mbti: 'ISTP',
      interests: '여행',
      skill: '외국어',
      food: '스테이크',
      color: '검정',
      music: '힙합, 락',
      dream: '외교관',
      motto: '과거를 두고 후회하지 않기',
      instagram: '@24.7lv',
      phone: '010-55XX-61XX',
    },
    12: {
      position: '홍보담당',
      age: '22',
      mbti: 'INTJ',
      interests: '여행, 운동, 자연, 문화 경험',
      skill: '스몰토크, 아이디어 발전시키기, 체력',
      food: '샤브샤브, 빵, 밥, 계란찜',
      color: '노랑',
      music: '외국 힙합, 한국 힙합, SZA, 빈지노, Steve Lacy, 제니',
      dream: '세계일주하기',
      motto: '보통의 존재로 행복하기',
      instagram: '@no0owis · blog.naver.com/no0owis',
      phone: '010-33XX-60XX',
    },
    13: {
      position: '총무',
      age: '17',
      mbti: 'ENFP',
      food: '과일 모찌',
      dream: '스튜어디스',
      motto: 'Sum-Zero',
      instagram: '@sua_ann',
      phone: '010-42XX-77XX',
    },
  },
  en: {
    1: {
      position: 'Deputy Team Leader',
      age: '19',
      mbti: 'ENTJ',
      interests: 'AI, design, economics, business, making things',
      skill: 'Making things',
      food: 'Zucchini pancake, mala tang, tteokbokki, spicy food',
      color: 'Achromatic (black/white/gray)',
      music: "“A Story That Becomes a Poem” by Shin Ji-hoon, ballads",
      dream: 'Becoming an expert in economics, SCM, and crisis management',
      motto: "DON'T COMPROMISE WITH MY SELF",
      instagram: '@hyum35',
      phone: '+82 10-53XX-29XX',
    },
    2: {
      position: 'Documentation Manager',
      age: '18',
      mbti: 'INTJ',
      interests: 'Language & culture, travel',
      skill: 'Foreign languages',
      food: 'Watermelon',
      color: 'Brown',
      music: 'Hip-hop, alternative',
      dream: 'To succeed',
      motto: "If it can't be done, make it happen!",
      instagram: '@bojoegm',
      phone: '+82 10-46XX-74XX',
    },
    3: {
      position: 'Public Relations Coordinator',
      age: '17',
      mbti: 'ISTJ',
      interests: 'Fashion',
      skill: 'Skating',
      food: 'Watermelon',
      color: 'Pink',
      music: 'Red Red · CORTIS · K-pop',
      dream: 'Fashion model',
      motto: 'Follow no trends. Set your own.',
      instagram: 'yeonz._zo',
      phone: '+82 10-88XX-84XX',
    },
    4: {
      position: 'Team Leader',
      age: '23',
      mbti: 'INFJ',
      interests: 'Healthy living / learning & insights',
      skill: 'Taking on new challenges',
      food: 'Bibimbap · sandwiches',
      color: 'Yellow',
      music: 'MIRACLE · NCT WISH · K-pop',
      dream: 'CEO / Living happily by giving back',
      motto: 'Live at my own pace',
      instagram: '@tjwlss',
      phone: '+82 10-56XX-85XX',
    },
    5: {
      position: 'Interpreter',
      age: 'Born 1994',
      interests: 'Travel, cats, movies',
      dream: 'Arabic translator',
      motto: 'Friendly · Detailed · Adventurous',
      phone: '+82 10-49XX-49XX',
    },
    6: {
      position: 'Discussion Activities Coordinator',
      age: '17',
      mbti: 'INTP',
      interests: 'Movies',
      skill: 'Presentation',
      food: 'Tteokbokki',
      color: 'Green',
      music: 'Korean retro music',
      dream: 'Travel around the world',
      motto: 'See the world.',
      instagram: '@soxwe_',
      phone: '+82 10-32XX-80XX',
    },
    7: {
      position: 'Cultural Presentation Coordinator',
      age: '17',
      mbti: 'ESTP',
      interests: 'Exercise',
      skill: 'Taekwondo',
      food: 'Hamburger',
      color: 'Pink',
      music: 'Love Attack · Lucianne · ballads',
      dream: 'Police officer',
      motto: 'Step by step, steadily.',
      instagram: '@tkd_dmsdn',
      phone: '+82 10-52XX-62XX',
    },
    8: {
      position: 'Documentation Manager',
      age: '18',
      mbti: 'INFP',
      interests: 'Reading, swimming, self-development, writing',
      skill: 'Writing, swimming',
      food: 'Tteokbokki, pizza',
      color: 'Jade',
      instagram: '@subeen.09',
      phone: '+82 10-67XX-69XX',
    },
    9: {
      position: 'Photo & Video Coordinator',
      age: '17',
      instagram: 'biinu.o',
      phone: '+82 10-92XX-33XX',
    },
    10: {
      position: 'Photo & Video Coordinator',
      age: '17',
      mbti: 'ISTP',
      interests: 'Travel, listening to music',
      color: 'Achromatic',
      music: 'Hip-hop, R&B',
      dream: 'Visit 100 countries',
      motto: 'I walk slowly, but I never walk backward.',
      instagram: '@eeeeung_',
      phone: '+82 10-58XX-07XX',
    },
    11: {
      position: 'Deputy Team Leader',
      age: '17',
      mbti: 'ISTP',
      interests: 'Travel',
      skill: 'Foreign languages',
      food: 'Steak',
      color: 'Black',
      music: 'Hip-hop, rock',
      dream: 'Diplomat',
      motto: 'Never regret the past',
      instagram: '@24.7lv',
      phone: '+82 10-55XX-61XX',
    },
    12: {
      position: 'Public Relations Coordinator',
      age: '22',
      mbti: 'INTJ',
      interests: 'Travel, exercise, nature, cultural experiences',
      skill: 'Small talk, developing ideas, stamina',
      food: 'Shabu-shabu, bread, rice, steamed egg',
      color: 'Yellow',
      music: 'International & Korean hip-hop, SZA, Beenzino, Steve Lacy, Jennie',
      dream: 'Travel around the world',
      motto: 'Be happy as an ordinary person',
      instagram: '@no0owis · blog.naver.com/no0owis',
      phone: '+82 10-33XX-60XX',
    },
    13: {
      position: 'Treasurer',
      age: '17',
      mbti: 'ENFP',
      food: 'Fruit mochi',
      dream: 'Flight attendant',
      motto: 'Sum-Zero',
      instagram: '@sua_ann',
      phone: '+82 10-42XX-77XX',
    },
  },
  ar: {
    1: {
      position: 'نائب رئيس الفريق',
      age: '19',
      mbti: 'ENTJ',
      interests: 'الذكاء الاصطناعي، التصميم، الاقتصاد، الإدارة، صنع الأشياء',
      skill: 'صنع الأشياء',
      food: 'فطيرة الكوسا، مالا تانغ، توكبوكي، الأطعمة الحارة',
      color: 'ألوان حيادية (أسود/أبيض/رمادي)',
      music: '"قصة تصبح قصيدة" لشين جي هون، موسيقى البالاد',
      dream: 'أن يصبح خبيرًا في الاقتصاد وإدارة سلاسل التوريد وإدارة الأزمات',
      motto: 'لا تساوم مع نفسك',
      instagram: '@hyum35',
      phone: '+82 10-53XX-29XX',
    },
    2: {
      position: 'مسؤول التوثيق',
      age: '18',
      mbti: 'INTJ',
      interests: 'اللغة والثقافة، السفر',
      skill: 'اللغات الأجنبية',
      food: 'البطيخ',
      color: 'بني',
      music: 'الهيب هوب، الألترناتيف',
      dream: 'تحقيق النجاح',
      motto: 'إن لم يكن ممكنًا، اجعله ممكنًا!',
      instagram: '@bojoegm',
      phone: '+82 10-46XX-74XX',
    },
    3: {
      position: 'منسق العلاقات العامة',
      age: '17',
      mbti: 'ISTJ',
      interests: 'الموضة',
      skill: 'التزلج',
      food: 'البطيخ',
      color: 'وردي',
      music: 'Red Red · CORTIS · K-pop',
      dream: 'عارضة أزياء',
      motto: 'لا تتبعي الموضة، بل ضعي معاييرك الخاصة',
      instagram: 'yeonz._zo',
      phone: '+82 10-88XX-84XX',
    },
    4: {
      position: 'رئيس الفريق',
      age: '23',
      mbti: 'INFJ',
      interests: 'الحياة الصحية / التعلم والفهم',
      skill: 'خوض تحديات جديدة',
      food: 'بيبيمباب · سندويشات',
      color: 'أصفر',
      music: 'MIRACLE · NCT WISH · K-pop',
      dream: 'أن تصبح مديرة تنفيذية وتعيش سعيدة بالعطاء',
      motto: 'عيشي بوتيرتك الخاصة',
      instagram: '@tjwlss',
      phone: '+82 10-56XX-85XX',
    },
    5: {
      position: 'مترجم',
      age: 'مواليد 1994',
      interests: 'السفر، القطط، الأفلام',
      dream: 'مترجمة لغة عربية',
      motto: 'ودودة · دقيقة · مغامِرة',
      phone: '+82 10-49XX-49XX',
    },
    6: {
      position: 'منسق الأنشطة النقاشية',
      age: '17',
      mbti: 'INTP',
      interests: 'الأفلام',
      skill: 'العروض التقديمية',
      food: 'توكبوكي',
      color: 'أخضر',
      music: 'موسيقى كورية ريترو',
      dream: 'السفر حول العالم',
      motto: 'انظر إلى العالم.',
      instagram: '@soxwe_',
      phone: '+82 10-32XX-80XX',
    },
    7: {
      position: 'منسق عرض الثقافة',
      age: '17',
      mbti: 'ESTP',
      interests: 'الرياضة',
      skill: 'التايكوندو',
      food: 'همبرغر',
      color: 'وردي',
      music: 'لوف أتاك · ليسين · بالاد',
      dream: 'ضابط شرطة',
      motto: 'خطوة بخطوة، بثبات.',
      instagram: '@tkd_dmsdn',
      phone: '+82 10-52XX-62XX',
    },
    8: {
      position: 'مسؤول التوثيق',
      age: '18',
      mbti: 'INFP',
      interests: 'القراءة، السباحة، تطوير الذات، الكتابة',
      skill: 'الكتابة، السباحة',
      food: 'توكبوكي، بيتزا',
      color: 'أخضر يشمي',
      instagram: '@subeen.09',
      phone: '+82 10-67XX-69XX',
    },
    9: {
      position: 'منسق التصوير الفوتوغرافي والفيديو',
      age: '17',
      instagram: 'biinu.o',
      phone: '+82 10-92XX-33XX',
    },
    10: {
      position: 'منسق التصوير الفوتوغرافي والفيديو',
      age: '17',
      mbti: 'ISTP',
      interests: 'السفر، الاستماع للموسيقى',
      color: 'ألوان حيادية',
      music: 'هيب هوب، آر أند بي',
      dream: 'زيارة 100 دولة',
      motto: 'أمشي ببطء، لكنني لا أعود إلى الخلف أبدًا.',
      instagram: '@eeeeung_',
      phone: '+82 10-58XX-07XX',
    },
    11: {
      position: 'نائب رئيس الفريق',
      age: '17',
      mbti: 'ISTP',
      interests: 'السفر',
      skill: 'اللغات الأجنبية',
      food: 'ستيك',
      color: 'أسود',
      music: 'الهيب هوب، الروك',
      dream: 'دبلوماسي',
      motto: 'لا تندم على الماضي أبدًا',
      instagram: '@24.7lv',
      phone: '+82 10-55XX-61XX',
    },
    12: {
      position: 'منسق العلاقات العامة',
      age: '22',
      mbti: 'INTJ',
      interests: 'السفر، الرياضة، الطبيعة، التجارب الثقافية',
      skill: 'الأحاديث الخفيفة، تطوير الأفكار، اللياقة البدنية',
      food: 'شابو شابو، الخبز، الأرز، البيض المطهو بالبخار',
      color: 'أصفر',
      music: 'هيب هوب عالمي وكوري، SZA، بينزينو، Steve Lacy، جيني',
      dream: 'السفر حول العالم',
      motto: 'أن تكون سعيدًا كشخص عادي',
      instagram: '@no0owis · blog.naver.com/no0owis',
      phone: '+82 10-33XX-60XX',
    },
    13: {
      position: 'أمين الصندوق',
      age: '17',
      mbti: 'ENFP',
      food: 'موتشي بالفواكه',
      dream: 'مضيفة طيران',
      motto: 'Sum-Zero',
      instagram: '@sua_ann',
      phone: '+82 10-42XX-77XX',
    },
  },
};
